using System;
using System.Collections.Generic;
using Language.Lua;

namespace LuaTranslator
{
    /// <summary>
    /// This file was generated. Do not edit.
    /// </summary>
    public class LuaTranslatorCodeMap
    {
        public static LuaValue EvaluateCachedCode(string luaString)
        {
            Func<LuaValue> luaValueCreator = null;
            if (Code.TryGetValue(luaString, out luaValueCreator))
            {
                LuaValue result = luaValueCreator();
                if (result.GetType() == typeof(LuaVariable)) result = ((LuaVariable)result).Dereference();
                return result;
            }
            return null;
        }

        public readonly static Dictionary<string, Func<LuaValue>> Code = new Dictionary<string, Func<LuaValue>>()
        {
            { "return Variable", LuaTranslatorCode.GeneratedLuaCode0 },
            { "return Actor", LuaTranslatorCode.GeneratedLuaCode1 },
            { "return Location", LuaTranslatorCode.GeneratedLuaCode2 },
            { "return Item", LuaTranslatorCode.GeneratedLuaCode3 },
            { "return StatusTable", LuaTranslatorCode.GeneratedLuaCode4 },
            { "return Conversation", LuaTranslatorCode.GeneratedLuaCode5 },
            { "return RelationshipTable", LuaTranslatorCode.GeneratedLuaCode6 },
            { "Variable[\"cemetery_met_gordon\"] = true", LuaTranslatorCode.GeneratedLuaCode7 },
            { "return not Variable[\"cemetery_met_gordon\"]", LuaTranslatorCode.GeneratedLuaCode8 },
            { "return Variable[\"cemetery_met_gordon\"]", LuaTranslatorCode.GeneratedLuaCode9 },
            { "return not Variable[\"cemetery_offered_gordon_deal\"] and Variable[\"cemetery_gordon_complained\"] and Variable[\"factory_smelled_forest\"]", LuaTranslatorCode.GeneratedLuaCode10 },
            { "Variable[\"cemetery_offered_gordon_deal\"] = true", LuaTranslatorCode.GeneratedLuaCode11 },
            { "return Variable[\"cemetery_gordon_explained_hes_dead\"]", LuaTranslatorCode.GeneratedLuaCode12 },
            { "Variable[\"cemetery_gordon_complained\"] = true", LuaTranslatorCode.GeneratedLuaCode13 },
            { "Variable[\"cemetery_gordon_explained_hes_dead\"] = true;", LuaTranslatorCode.GeneratedLuaCode14 },
            { "Variable[\"cemetery_govi_started\"] = true;", LuaTranslatorCode.GeneratedLuaCode15 },
            { "return Variable[\"cemetery_govi_monied\"] and Variable[\"cemetery_govi_pendanted\"] and Variable[\"cemetery_govi_inked\"]", LuaTranslatorCode.GeneratedLuaCode16 },
            { "Variable[\"cemetery_govi_complete\"] = true;", LuaTranslatorCode.GeneratedLuaCode17 },
            { "return not (Variable[\"cemetery_govi_monied\"] and Variable[\"cemetery_govi_pendanted\"] and Variable[\"cemetery_govi_inked\"])", LuaTranslatorCode.GeneratedLuaCode18 },
            { "SetDialogueMemory(462,6);\nSetDialogueMemory(462,8);\nSetDialogueMemory(462,13);", LuaTranslatorCode.GeneratedLuaCode19 },
            { "InventoryRemoveItem(\"Ink Bottle\");\nVariable[\"cemetery_govi_inked\"] = true;", LuaTranslatorCode.GeneratedLuaCode20 },
            { "SetDialogueMemory(462,7);\nSetDialogueMemory(462,9);\nSetDialogueMemory(462,10);", LuaTranslatorCode.GeneratedLuaCode21 },
            { "Variable[\"cemetery_govi_pendanted\"] = true;", LuaTranslatorCode.GeneratedLuaCode22 },
            { "return not (Variable[\"cemetery_govi_monied\"] and Variable[\"cemetery_govi_pendanted\"] and Variable[\"cemetery_govi_inked\"]) and (Variable[\"cemetery_govi_monied\"] or Variable[\"cemetery_govi_pendanted\"] or Variable[\"cemetery_govi_inked\"])", LuaTranslatorCode.GeneratedLuaCode23 },
            { "return not (Variable[\"cemetery_govi_monied\"] or Variable[\"cemetery_govi_pendanted\"] or Variable[\"cemetery_govi_inked\"])", LuaTranslatorCode.GeneratedLuaCode24 },
            { "return Variable[\"cemetery_govi_inked\"] ", LuaTranslatorCode.GeneratedLuaCode25 },
            { "return Variable[\"cemetery_govi_pendanted\"]", LuaTranslatorCode.GeneratedLuaCode26 },
            { "return not Variable[\"cemetery_govi_pendanted\"]", LuaTranslatorCode.GeneratedLuaCode27 },
            { "return Variable[\"cemetery_govi_monied\"]", LuaTranslatorCode.GeneratedLuaCode28 },
            { "return not Variable[\"cemetery_govi_monied\"]", LuaTranslatorCode.GeneratedLuaCode29 },
            { "return not Variable[\"cemetery_govi_inked\"] ", LuaTranslatorCode.GeneratedLuaCode30 },
            { "Variable[\"cemetery_govi_monied\"] = true;", LuaTranslatorCode.GeneratedLuaCode31 },
            { "return not InventoryContains(\"LeMoon Mausoleum Key\")", LuaTranslatorCode.GeneratedLuaCode32 },
            { "return Variable[\"owner_honer_active\"]", LuaTranslatorCode.GeneratedLuaCode33 },
            { "return not Variable[\"owner_honer_completed\"]", LuaTranslatorCode.GeneratedLuaCode34 },
            { "return not Variable[\"owner_honer_active\"]", LuaTranslatorCode.GeneratedLuaCode35 },
            { "return Variable[\"owner_honer_completed\"]", LuaTranslatorCode.GeneratedLuaCode36 },
            { "Variable[\"cemetery_lemoon_unlocked\"] = true;", LuaTranslatorCode.GeneratedLuaCode37 },
            { "return InventoryContains(\"LeMoon Mausoleum Key\")", LuaTranslatorCode.GeneratedLuaCode38 },
            { "Variable[\"global_act_1_quest_stage\"] = \"InvestigateLaughton\";\nVariable[\"owner_honer_active\"] = false;\nVariable[\"owner_honer_completed\"] = true;", LuaTranslatorCode.GeneratedLuaCode39 },
            { "InventoryRemoveItem(\"Owner Honer Pendant\");\nInventoryAddItem(\"Pendant\");", LuaTranslatorCode.GeneratedLuaCode40 },
            { "return not Variable[\"cemetery_met_eartha\"]", LuaTranslatorCode.GeneratedLuaCode41 },
            { "return Variable[\"cemetery_met_eartha\"]", LuaTranslatorCode.GeneratedLuaCode42 },
            { "Variable[\"cemetery_met_eartha\"] = true", LuaTranslatorCode.GeneratedLuaCode43 },
            { "return not Variable[\"cemetery_gave_eartha_shovel\"] and Variable[\"global_act_1_quest_stage\"] == \"InvestigateLaughton\"", LuaTranslatorCode.GeneratedLuaCode44 },
            { "Variable[\"cemetery_gordon_owns_cemetery\"] = true", LuaTranslatorCode.GeneratedLuaCode45 },
            { "return not Variable[\"cemetery_lemoon_unlocked\"]", LuaTranslatorCode.GeneratedLuaCode46 },
            { "Variable[\"cemetery_eartha_wants_shovel\"] = true", LuaTranslatorCode.GeneratedLuaCode47 },
            { "Variable[\"cemetery_gave_eartha_shovel\"] = true;\nInventoryRemoveItem(\"Shovel\");", LuaTranslatorCode.GeneratedLuaCode48 },
            { "return Variable[\"cemetery_eartha_wants_shovel\"] and InventoryContains(\"Shovel\")", LuaTranslatorCode.GeneratedLuaCode49 },
            { "return Variable[\"global_act_1_quest_stage\"] == \"InvestigateLaughton\"", LuaTranslatorCode.GeneratedLuaCode50 },
            { "x = RandomChoice(\"Faded Tombstones\",3);", LuaTranslatorCode.GeneratedLuaCode51 },
            { "return x == 1", LuaTranslatorCode.GeneratedLuaCode52 },
            { "return x == 2", LuaTranslatorCode.GeneratedLuaCode53 },
            { "return x == 3", LuaTranslatorCode.GeneratedLuaCode54 },
            { "return Variable[\"global_current_act\"] ~= 3", LuaTranslatorCode.GeneratedLuaCode55 },
            { "return Variable[\"global_current_act\"] == 3", LuaTranslatorCode.GeneratedLuaCode56 },
            { "Variable[\"cemetery_esmereldas_coffin_open\"] = true;", LuaTranslatorCode.GeneratedLuaCode57 },
            { "return not Variable[\"cemetery_esmereldas_coffin_open\"]", LuaTranslatorCode.GeneratedLuaCode58 },
            { "return Variable[\"cemetery_esmereldas_coffin_open\"]", LuaTranslatorCode.GeneratedLuaCode59 },
            { "food = \"mahi mahi\";\nVariable[\"chic_mahi_ordered\"] = true;", LuaTranslatorCode.GeneratedLuaCode60 },
            { "return not Variable[\"chic_mahi_ordered\"]", LuaTranslatorCode.GeneratedLuaCode61 },
            { "food = \"snapper\";\nVariable[\"chic_snapper_ordered\"] = true;", LuaTranslatorCode.GeneratedLuaCode62 },
            { "return not Variable[\"chic_snapper_ordered\"]", LuaTranslatorCode.GeneratedLuaCode63 },
            { "Variable[\"chic_mojito_ordered\"] = true;", LuaTranslatorCode.GeneratedLuaCode64 },
            { "return not Variable[\"chic_mojito_ordered\"]", LuaTranslatorCode.GeneratedLuaCode65 },
            { "Variable[\"chic_martini_ordered\"] = true;", LuaTranslatorCode.GeneratedLuaCode66 },
            { "return not Variable[\"chic_martini_ordered\"]", LuaTranslatorCode.GeneratedLuaCode67 },
            { "Variable[\"chic_punch_ordered\"] = true;", LuaTranslatorCode.GeneratedLuaCode68 },
            { "return not Variable[\"chic_punch_ordered\"]", LuaTranslatorCode.GeneratedLuaCode69 },
            { "food = \"fugo\";\nVariable[\"chic_fugo_ordered\"] = true;", LuaTranslatorCode.GeneratedLuaCode70 },
            { "return not Variable[\"chic_fugo_ordered\"]", LuaTranslatorCode.GeneratedLuaCode71 },
            { "return not Variable[\"chic_menu_known\"]", LuaTranslatorCode.GeneratedLuaCode72 },
            { "return Variable[\"chic_menu_known\"]", LuaTranslatorCode.GeneratedLuaCode73 },
            { "SubtractMoney(2);\nSetDialogueMemory(9,97);", LuaTranslatorCode.GeneratedLuaCode74 },
            { "return Variable[\"chic_told_food_joke\"]", LuaTranslatorCode.GeneratedLuaCode75 },
            { "SubtractMoney(1);\nSetDialogueMemory(9,111);", LuaTranslatorCode.GeneratedLuaCode76 },
            { "Variable[\"chic_told_food_joke\"] = true;", LuaTranslatorCode.GeneratedLuaCode77 },
            { "return not Variable[\"chic_told_food_joke\"]", LuaTranslatorCode.GeneratedLuaCode78 },
            { "return Variable[\"chic_told_drink_joke\"]", LuaTranslatorCode.GeneratedLuaCode79 },
            { "Variable[\"chic_told_drink_joke\"] = true;", LuaTranslatorCode.GeneratedLuaCode80 },
            { "return not Variable[\"chic_told_drink_joke\"]", LuaTranslatorCode.GeneratedLuaCode81 },
            { "return Variable[\"chic_punch_ordered\"] and Variable[\"chic_mojito_ordered\"] and Variable[\"chic_martini_ordered\"]", LuaTranslatorCode.GeneratedLuaCode82 },
            { "return food == \"fugo\"", LuaTranslatorCode.GeneratedLuaCode83 },
            { "return Variable[\"chic_fugo_ordered\"]", LuaTranslatorCode.GeneratedLuaCode84 },
            { "return food == \"mahi mahi\"", LuaTranslatorCode.GeneratedLuaCode85 },
            { "return food == \"snapper\"", LuaTranslatorCode.GeneratedLuaCode86 },
            { "return not (Variable[\"chic_punch_ordered\"] and Variable[\"chic_mojito_ordered\"] and Variable[\"chic_martini_ordered\"])", LuaTranslatorCode.GeneratedLuaCode87 },
            { "return Variable[\"chic_mahi_ordered\"]", LuaTranslatorCode.GeneratedLuaCode88 },
            { "return Variable[\"chic_snapper_ordered\"]", LuaTranslatorCode.GeneratedLuaCode89 },
            { "return Variable[\"chic_martini_ordered\"]", LuaTranslatorCode.GeneratedLuaCode90 },
            { "return Variable[\"chic_mojito_ordered\"]", LuaTranslatorCode.GeneratedLuaCode91 },
            { "return Variable[\"chic_punch_ordered\"]", LuaTranslatorCode.GeneratedLuaCode92 },
            { "Variable[\"chic_menu_known\"] = true", LuaTranslatorCode.GeneratedLuaCode93 },
            { "return not (Variable[\"chic_met_kiki\"] and Variable[\"chic_kiki_is_ready_to_talk\"])", LuaTranslatorCode.GeneratedLuaCode94 },
            { "return Variable[\"chic_met_kiki\"] and Variable[\"chic_kiki_is_ready_to_talk\"]", LuaTranslatorCode.GeneratedLuaCode95 },
            { "Variable[\"chic_kiki_is_ready_to_talk\"] = true;\nSetDialogueMemory(8,149);", LuaTranslatorCode.GeneratedLuaCode96 },
            { "return not Variable[\"chic_kiki_is_ready_to_talk\"]", LuaTranslatorCode.GeneratedLuaCode97 },
            { "return Variable[\"mansion_learned_of_kiki\"]", LuaTranslatorCode.GeneratedLuaCode98 },
            { "Variable[\"chic_met_kiki\"] = true", LuaTranslatorCode.GeneratedLuaCode99 },
            { "Variable[\"chic_kiki_saw_pendant\"] = true;", LuaTranslatorCode.GeneratedLuaCode100 },
            { "return Variable[\"global_act_1_quest_stage\"] == \"FindPendantOwner\"", LuaTranslatorCode.GeneratedLuaCode101 },
            { "return Variable[\"mansion_told_lemoon_story\"] or Variable[\"cc_gordon_told_lemoon_story\"]", LuaTranslatorCode.GeneratedLuaCode102 },
            { "return Variable[\"ll_refused_to_talk\"]", LuaTranslatorCode.GeneratedLuaCode103 },
            { "return not Variable[\"ll_refused_to_talk\"]", LuaTranslatorCode.GeneratedLuaCode104 },
            { "Variable[\"chic_kiki_left_restaurant\"] = true;", LuaTranslatorCode.GeneratedLuaCode105 },
            { "return Variable[\"cemetery_gave_eartha_shovel\"]", LuaTranslatorCode.GeneratedLuaCode106 },
            { "return Variable[\"chic_kiki_saw_pendant\"]", LuaTranslatorCode.GeneratedLuaCode107 },
            { "return not Variable[\"chic_kiki_saw_pendant\"]", LuaTranslatorCode.GeneratedLuaCode108 },
            { "return not Variable[\"mansion_learned_of_kiki\"]", LuaTranslatorCode.GeneratedLuaCode109 },
            { "return not Variable[\"chic_kiki_left_restaurant\"] ", LuaTranslatorCode.GeneratedLuaCode110 },
            { "return Variable[\"chic_kiki_left_restaurant\"]", LuaTranslatorCode.GeneratedLuaCode111 },
            { "return not Variable[\"chic_met_kiki\"]", LuaTranslatorCode.GeneratedLuaCode112 },
            { "return Variable[\"chic_met_kiki\"]", LuaTranslatorCode.GeneratedLuaCode113 },
            { "return Variable[\"chic_kiki_is_ready_to_talk\"]", LuaTranslatorCode.GeneratedLuaCode114 },
            { "return Variable[\"chic_fugo_gland_acquired\"]", LuaTranslatorCode.GeneratedLuaCode115 },
            { "Variable[\"chic_fugo_gland_acquired\"] = true;", LuaTranslatorCode.GeneratedLuaCode116 },
            { "return not Variable[\"chic_fugo_gland_acquired\"]", LuaTranslatorCode.GeneratedLuaCode117 },
            { "return Variable[\"chic_know_need_room_key\"]", LuaTranslatorCode.GeneratedLuaCode118 },
            { "Variable[\"chic_elevator_unlocked\"] = true;\nInventoryRemoveItem(\"Kiki's Room Key\");", LuaTranslatorCode.GeneratedLuaCode119 },
            { "return InventoryContains(\"Kiki's Room Key\")", LuaTranslatorCode.GeneratedLuaCode120 },
            { "Variable[\"chic_know_need_room_key\"] = true", LuaTranslatorCode.GeneratedLuaCode121 },
            { "return not Variable[\"chic_can_enter_marys_room\"] ", LuaTranslatorCode.GeneratedLuaCode122 },
            { "return not InventoryContains(\"Kiki's Room Key\")", LuaTranslatorCode.GeneratedLuaCode123 },
            { "return not Variable[\"chic_elevator_unlocked\"] and Variable[\"chic_know_need_room_key\"]", LuaTranslatorCode.GeneratedLuaCode124 },
            { "Variable[\"chic_took_flower\"] = true;", LuaTranslatorCode.GeneratedLuaCode125 },
            { "return not Variable[\"chic_took_flower\"]", LuaTranslatorCode.GeneratedLuaCode126 },
            { "return Variable[\"chic_took_flower\"]", LuaTranslatorCode.GeneratedLuaCode127 },
            { "return not Variable[\"ll_gave_kiki_photos\"]", LuaTranslatorCode.GeneratedLuaCode128 },
            { "return InventoryContains(\"Incriminating Photos\")", LuaTranslatorCode.GeneratedLuaCode129 },
            { "InventoryRemoveItem(\"Incriminating Photos\");\nVariable[\"ll_gave_kiki_photos\"] = true;", LuaTranslatorCode.GeneratedLuaCode130 },
            { "return Variable[\"ll_gave_kiki_photos\"]", LuaTranslatorCode.GeneratedLuaCode131 },
            { "return Variable[\"ll_gave_theodore_photos\"]", LuaTranslatorCode.GeneratedLuaCode132 },
            { "Variable[\"chic_mary_ready_for_stake_out\"] = true", LuaTranslatorCode.GeneratedLuaCode133 },
            { "return not Variable[\"chic_mary_ready_for_stake_out\"] ", LuaTranslatorCode.GeneratedLuaCode134 },
            { "return Variable[\"cemetery_gordon_owns_cemetery\"]", LuaTranslatorCode.GeneratedLuaCode135 },
            { "return Variable[\"cc_gordon_told_lemoon_story\"] or Variable[\"mansion_told_lemoon_story\"]", LuaTranslatorCode.GeneratedLuaCode136 },
            { "return Variable[\"cc_gordon_told_lemoon_story\"]", LuaTranslatorCode.GeneratedLuaCode137 },
            { "return Variable[\"mansion_told_lemoon_story\"]", LuaTranslatorCode.GeneratedLuaCode138 },
            { "return Variable[\"cc_mary_knows_lemoon\"]", LuaTranslatorCode.GeneratedLuaCode139 },
            { "return Variable[\"global_act_1_quest_stage\"] == \"ConfrontVictorAboutJournal\" or Variable[\"global_act_1_quest_stage\"] == \"BombDeployed\" ", LuaTranslatorCode.GeneratedLuaCode140 },
            { "Variable[\"chic_explained_laughton_to_mary\"] = true", LuaTranslatorCode.GeneratedLuaCode141 },
            { "return (not Variable[\"chic_explained_laughton_to_mary\"]) or (not Variable[\"ll_cant_fit_in_shaft\"] and Variable[\"chic_explained_laughton_to_mary\"])", LuaTranslatorCode.GeneratedLuaCode142 },
            { "Variable[\"ll_is_stake_out\"] = true", LuaTranslatorCode.GeneratedLuaCode143 },
            { "return Variable[\"chic_explained_laughton_to_mary\"] and Variable[\"ll_cant_fit_in_shaft\"]", LuaTranslatorCode.GeneratedLuaCode144 },
            { "return Variable[\"chic_mary_ready_for_stake_out\"]", LuaTranslatorCode.GeneratedLuaCode145 },
            { "return not Variable[\"ll_photos_taken\"]", LuaTranslatorCode.GeneratedLuaCode146 },
            { "Variable[\"chic_told_mary_about_pendant\"] = true", LuaTranslatorCode.GeneratedLuaCode147 },
            { "return not Variable[\"chic_told_mary_about_pendant\"]", LuaTranslatorCode.GeneratedLuaCode148 },
            { "return Variable[\"chic_told_mary_about_pendant\"]", LuaTranslatorCode.GeneratedLuaCode149 },
            { "return Variable[\"global_act_1_quest_stage\"] == \"AcquireJournal\"", LuaTranslatorCode.GeneratedLuaCode150 },
            { "return Variable[\"global_act_1_quest_stage\"] == \"InvestigateLaughton\" or Variable[\"global_act_1_quest_stage\"] == \"AcquireJournal\"", LuaTranslatorCode.GeneratedLuaCode151 },
            { "Variable[\"cc_mary_knows_lemoon\"] = true;", LuaTranslatorCode.GeneratedLuaCode152 },
            { "return not Variable[\"cc_mary_knows_lemoon\"]", LuaTranslatorCode.GeneratedLuaCode153 },
            { "return not InventoryContains(\"Camera\")", LuaTranslatorCode.GeneratedLuaCode154 },
            { "return InventoryContains(\"Camera\")", LuaTranslatorCode.GeneratedLuaCode155 },
            { "Variable[\"chic_can_enter_kikis_room\"] = true", LuaTranslatorCode.GeneratedLuaCode156 },
            { "Variable[\"chic_learned_kiki_door_name\"] = true", LuaTranslatorCode.GeneratedLuaCode157 },
            { "Variable[\"chic_can_enter_marys_room\"] = true", LuaTranslatorCode.GeneratedLuaCode158 },
            { "x = RandomChoice(\"Apply Item to Unapplyable\",2);", LuaTranslatorCode.GeneratedLuaCode159 },
            { "x = RandomChoice(\"Combine Uncombinable\",3);", LuaTranslatorCode.GeneratedLuaCode160 },
            { "return (SceneName() == \"Forest (Entrance)\")", LuaTranslatorCode.GeneratedLuaCode161 },
            { "return not Variable[\"factory_govi_active\"] and InventoryContains(\"Govi\")", LuaTranslatorCode.GeneratedLuaCode162 },
            { "return not InventoryContains(\"Govi\")", LuaTranslatorCode.GeneratedLuaCode163 },
            { "return Variable[\"global_current_act\"] ~= 1", LuaTranslatorCode.GeneratedLuaCode164 },
            { "return Variable[\"global_current_act\"] == 1", LuaTranslatorCode.GeneratedLuaCode165 },
            { "x = RandomChoice(\"Talk to Tourist\",4);", LuaTranslatorCode.GeneratedLuaCode166 },
            { "return Variable[\"global_early_gun_talk_prevented\"]", LuaTranslatorCode.GeneratedLuaCode167 },
            { "return x == 4", LuaTranslatorCode.GeneratedLuaCode168 },
            { "Variable[\"global_early_gun_talk_prevented\"] = true;\nx = 2;", LuaTranslatorCode.GeneratedLuaCode169 },
            { "return not Variable[\"global_early_gun_talk_prevented\"]", LuaTranslatorCode.GeneratedLuaCode170 },
            { "x = RandomChoice(\"Talk to Zombie\",6);", LuaTranslatorCode.GeneratedLuaCode171 },
            { "return Variable[\"global_talked_to_zombie\"]", LuaTranslatorCode.GeneratedLuaCode172 },
            { "return x == 5", LuaTranslatorCode.GeneratedLuaCode173 },
            { "return x == 6", LuaTranslatorCode.GeneratedLuaCode174 },
            { "x = 3;\nVariable[\"global_talked_to_zombie\"] = true;", LuaTranslatorCode.GeneratedLuaCode175 },
            { "return not Variable[\"global_talked_to_zombie\"]", LuaTranslatorCode.GeneratedLuaCode176 },
            { "x = RandomChoice(\"Use Unusable\",3);", LuaTranslatorCode.GeneratedLuaCode177 },
            { "return Variable[\"global_act_1_quest_stage\"] == \"Tutorial\"", LuaTranslatorCode.GeneratedLuaCode178 },
            { "return Variable[\"global_act_1_quest_stage\"] == \"AnswerTelephone\"", LuaTranslatorCode.GeneratedLuaCode179 },
            { "return Variable[\"global_act_1_quest_stage\"] == \"Opening\"", LuaTranslatorCode.GeneratedLuaCode180 },
            { "return Variable[\"global_act_1_quest_stage\"] == \"ConfrontVictorAboutJournal\"", LuaTranslatorCode.GeneratedLuaCode181 },
            { "return Variable[\"global_act_1_quest_stage\"] == \"BombDeployed\"", LuaTranslatorCode.GeneratedLuaCode182 },
            { "return Variable[\"global_act_1_quest_stage\"] == \"VDWasBombed\"", LuaTranslatorCode.GeneratedLuaCode183 },
            { "return Variable[\"global_act_2_quest_stage\"] == \"FollowBadGuys\"", LuaTranslatorCode.GeneratedLuaCode184 },
            { "return Variable[\"global_act_2_quest_stage\"] == \"PowerTheCrane\"", LuaTranslatorCode.GeneratedLuaCode185 },
            { "return Variable[\"global_act_2_quest_stage\"] == \"DrainTheLake\"", LuaTranslatorCode.GeneratedLuaCode186 },
            { "return Variable[\"global_act_2_quest_stage\"] == \"HandleTheHounfo\"", LuaTranslatorCode.GeneratedLuaCode187 },
            { "return Variable[\"global_act_2_quest_stage\"] == \"ReturnToBeach\"", LuaTranslatorCode.GeneratedLuaCode188 },
            { "return Variable[\"global_act_3_quest_stage\"] == \"GetTheGovi\"", LuaTranslatorCode.GeneratedLuaCode189 },
            { "return Variable[\"global_act_3_quest_stage\"] == \"OpenTheSafe\"", LuaTranslatorCode.GeneratedLuaCode190 },
            { "return Variable[\"global_act_3_quest_stage\"] == \"SaveBaronSamedi\"", LuaTranslatorCode.GeneratedLuaCode191 },
            { "return Variable[\"global_act_3_quest_stage\"] == \"EndGame\"", LuaTranslatorCode.GeneratedLuaCode192 },
            { "return Variable[\"cemetery_eartha_wants_shovel\"]", LuaTranslatorCode.GeneratedLuaCode193 },
            { "return not Variable[\"cemetery_gave_eartha_shovel\"]", LuaTranslatorCode.GeneratedLuaCode194 },
            { "return Variable[\"ll_photos_taken\"]", LuaTranslatorCode.GeneratedLuaCode195 },
            { "return not (Variable[\"ll_gave_kiki_photos\"] or Variable[\"ll_gave_theodore_photos\"])", LuaTranslatorCode.GeneratedLuaCode196 },
            { "return Variable[\"ll_gave_kiki_photos\"] or Variable[\"ll_gave_theodore_photos\"]", LuaTranslatorCode.GeneratedLuaCode197 },
            { "return Variable[\"cc_personal_passcode\"] == \"\"", LuaTranslatorCode.GeneratedLuaCode198 },
            { "return Variable[\"cc_personal_passcode\"] ~= \"\"", LuaTranslatorCode.GeneratedLuaCode199 },
            { "return not Variable[\"yacht_examined_lifeboat\"]", LuaTranslatorCode.GeneratedLuaCode200 },
            { "return Variable[\"yacht_examined_lifeboat\"]", LuaTranslatorCode.GeneratedLuaCode201 },
            { "return not Variable[\"yacht_fusebox_fixed\"]", LuaTranslatorCode.GeneratedLuaCode202 },
            { "return Variable[\"yacht_fusebox_fixed\"]", LuaTranslatorCode.GeneratedLuaCode203 },
            { "return not Variable[\"yacht_examined_fusebox\"]", LuaTranslatorCode.GeneratedLuaCode204 },
            { "return Variable[\"yacht_examined_fusebox\"]", LuaTranslatorCode.GeneratedLuaCode205 },
            { "return not Variable[\"yacht_ritual_over\"]", LuaTranslatorCode.GeneratedLuaCode206 },
            { "return Variable[\"yacht_ritual_over\"]", LuaTranslatorCode.GeneratedLuaCode207 },
            { "return not Variable[\"if_francois_gave_quest\"]", LuaTranslatorCode.GeneratedLuaCode208 },
            { "return Variable[\"if_francois_gave_quest\"]", LuaTranslatorCode.GeneratedLuaCode209 },
            { "return not Variable[\"if_finished_possession\"]", LuaTranslatorCode.GeneratedLuaCode210 },
            { "return Variable[\"if_finished_possession\"]", LuaTranslatorCode.GeneratedLuaCode211 },
            { "return not Variable[\"if_francois_lied\"]", LuaTranslatorCode.GeneratedLuaCode212 },
            { "return Variable[\"if_francois_lied\"]", LuaTranslatorCode.GeneratedLuaCode213 },
            { "return not (Variable[\"pl_cane_state\"] == \"Used\" and Variable[\"pl_hat_state\"] == \"Used\" and Variable[\"pl_pipe_state\"] == \"Used\")", LuaTranslatorCode.GeneratedLuaCode214 },
            { "return Variable[\"pl_cane_state\"] == \"Used\" and Variable[\"pl_hat_state\"] == \"Used\" and Variable[\"pl_pipe_state\"] == \"Used\"", LuaTranslatorCode.GeneratedLuaCode215 },
            { "return not Variable[\"cemetery_eartha_wants_shovel\"]", LuaTranslatorCode.GeneratedLuaCode216 },
            { "return not IsDoorKnocking()", LuaTranslatorCode.GeneratedLuaCode217 },
            { "return IsDoorKnocking()", LuaTranslatorCode.GeneratedLuaCode218 },
            { "return not Variable[\"factory_smelled_forest\"]", LuaTranslatorCode.GeneratedLuaCode219 },
            { "return Variable[\"factory_smelled_forest\"]", LuaTranslatorCode.GeneratedLuaCode220 },
            { "return not Variable[\"factory_safe_open\"]", LuaTranslatorCode.GeneratedLuaCode221 },
            { "return Variable[\"factory_safe_open\"]", LuaTranslatorCode.GeneratedLuaCode222 },
            { "return not Variable[\"factory_fire_started\"]", LuaTranslatorCode.GeneratedLuaCode223 },
            { "return Variable[\"factory_fire_started\"]", LuaTranslatorCode.GeneratedLuaCode224 },
            { "return not Variable[\"dhb_have_grammys_book\"]", LuaTranslatorCode.GeneratedLuaCode225 },
            { "return Variable[\"dhb_have_grammys_book\"]", LuaTranslatorCode.GeneratedLuaCode226 },
            { "Variable[\"cc_met_gordon\"] = true", LuaTranslatorCode.GeneratedLuaCode227 },
            { "return not Variable[\"cc_met_gordon\"]", LuaTranslatorCode.GeneratedLuaCode228 },
            { "return Variable[\"cc_met_gordon\"]", LuaTranslatorCode.GeneratedLuaCode229 },
            { "Variable[\"cc_gordon_knows_lemoon\"] = true;\nSetDialogueMemory(121,201);", LuaTranslatorCode.GeneratedLuaCode230 },
            { "return not Variable[\"cc_gordon_knows_lemoon\"]", LuaTranslatorCode.GeneratedLuaCode231 },
            { "Variable[\"cc_gordon_told_lemoon_story\"] = true;", LuaTranslatorCode.GeneratedLuaCode232 },
            { "Variable[\"cc_can_ask_about_chocolate\"] = true", LuaTranslatorCode.GeneratedLuaCode233 },
            { "return Variable[\"cc_executive_approval_explained\"]", LuaTranslatorCode.GeneratedLuaCode234 },
            { "return not Variable[\"cc_gordon_is_poisoned\"]", LuaTranslatorCode.GeneratedLuaCode235 },
            { "return Variable[\"mansion_victor_blamed_gordon\"]", LuaTranslatorCode.GeneratedLuaCode236 },
            { "SetDialogueMemory(121,142);\nSetDialogueMemory(121,210);\nSetDialogueMemory(121,211);", LuaTranslatorCode.GeneratedLuaCode237 },
            { "return Variable[\"cc_can_ask_about_chocolate\"]", LuaTranslatorCode.GeneratedLuaCode238 },
            { "return InventoryContains(\"Poisoned Chocolates\")", LuaTranslatorCode.GeneratedLuaCode239 },
            { "SetDialogueMemory(121,209);\nSetDialogueMemory(121,179);", LuaTranslatorCode.GeneratedLuaCode240 },
            { "return not Variable[\"cc_gordon_mentioned_chocolates\"]", LuaTranslatorCode.GeneratedLuaCode241 },
            { "Variable[\"cc_gordon_mentioned_chocolates\"] = true;\nSetDialogueMemory(121,180);\nSetDialogueMemory(121,209);", LuaTranslatorCode.GeneratedLuaCode242 },
            { "return Variable[\"cc_gordon_is_poisoned\"]", LuaTranslatorCode.GeneratedLuaCode243 },
            { "SetDialogueMemory(121,206);\nSetDialogueMemory(121,207);", LuaTranslatorCode.GeneratedLuaCode244 },
            { "return Variable[\"cc_gordon_knows_lemoon\"]", LuaTranslatorCode.GeneratedLuaCode245 },
            { "SetDialogueMemory(121,199);", LuaTranslatorCode.GeneratedLuaCode246 },
            { "return Variable[\"cc_gordon_mentioned_chocolates\"]", LuaTranslatorCode.GeneratedLuaCode247 },
            { "Variable[\"cc_gordon_is_poisoned\"] = true", LuaTranslatorCode.GeneratedLuaCode248 },
            { "return Variable[\"cc_acquired_override\"]", LuaTranslatorCode.GeneratedLuaCode249 },
            { "Variable[\"cc_acquired_override\"] = true;", LuaTranslatorCode.GeneratedLuaCode250 },
            { "return not Variable[\"cc_acquired_override\"]", LuaTranslatorCode.GeneratedLuaCode251 },
            { "return not Variable[\"global_read_francois_journal\"]", LuaTranslatorCode.GeneratedLuaCode252 },
            { "return not (CanAfford(245) and InventoryContains(\"Executive Approval Form\"))", LuaTranslatorCode.GeneratedLuaCode253 },
            { "return Variable[\"mansion_argument_finished\"]", LuaTranslatorCode.GeneratedLuaCode254 },
            { "return CanAfford(245) and InventoryContains(\"Executive Approval Form\")", LuaTranslatorCode.GeneratedLuaCode255 },
            { "Variable[\"cc_personal_passcode\"] = Variable[\"cc_passcode_buffer\"];\nVariable[\"cc_passcode_buffer\"] = \"\";", LuaTranslatorCode.GeneratedLuaCode256 },
            { "UnsetDialogueMemory(120, 46);", LuaTranslatorCode.GeneratedLuaCode257 },
            { "return Variable[\"cc_crumbsford_gone_after_journal\"]", LuaTranslatorCode.GeneratedLuaCode258 },
            { "Variable[\"cc_executive_approval_explained\"] = true", LuaTranslatorCode.GeneratedLuaCode259 },
            { "return not InventoryContains(\"Executive Approval Form\")", LuaTranslatorCode.GeneratedLuaCode260 },
            { "return Variable[\"global_act_1_quest_stage\"] ~= \"AcquireJournal\"", LuaTranslatorCode.GeneratedLuaCode261 },
            { "return not Variable[\"cc_executive_approval_explained\"]", LuaTranslatorCode.GeneratedLuaCode262 },
            { "return not Variable[\"mansion_argument_finished\"]", LuaTranslatorCode.GeneratedLuaCode263 },
            { "InventoryRemoveItem(\"Candle\");\nInventoryAddItem(\"Black Candle\");", LuaTranslatorCode.GeneratedLuaCode264 },
            { "return Variable[\"global_current_act\"] > 1", LuaTranslatorCode.GeneratedLuaCode265 },
            { "Variable[\"cc_passcode_buffer\"] = \"\"", LuaTranslatorCode.GeneratedLuaCode266 },
            { "return not IsSafeDepositCodeCorrect()", LuaTranslatorCode.GeneratedLuaCode267 },
            { "return IsSafeDepositCodeCorrect()", LuaTranslatorCode.GeneratedLuaCode268 },
            { "Variable[\"global_read_francois_journal\"] = true", LuaTranslatorCode.GeneratedLuaCode269 },
            { "Variable[\"global_act_1_quest_stage\"] = \"ConfrontVictorAboutJournal\"", LuaTranslatorCode.GeneratedLuaCode270 },
            { "return Variable[\"global_read_francois_journal\"]", LuaTranslatorCode.GeneratedLuaCode271 },
            { "return Variable[\"dhb_minigame_completed\"]", LuaTranslatorCode.GeneratedLuaCode272 },
            { "return not Variable[\"dhb_minigame_completed\"]", LuaTranslatorCode.GeneratedLuaCode273 },
            { "return Variable[\"dhb_minigame_upgrade_required\"]", LuaTranslatorCode.GeneratedLuaCode274 },
            { "return not Variable[\"dhb_minigame_upgrade_required\"]", LuaTranslatorCode.GeneratedLuaCode275 },
            { "Variable[\"dhb_have_grammys_book\"] = true;", LuaTranslatorCode.GeneratedLuaCode276 },
            { "return Variable[\"mansion_met_victor\"] or Variable[\"dhb_ricky_mentioned_victor_and_gordon\"]", LuaTranslatorCode.GeneratedLuaCode277 },
            { "return Variable[\"cc_met_gordon\"] or Variable[\"dhb_ricky_mentioned_victor_and_gordon\"]", LuaTranslatorCode.GeneratedLuaCode278 },
            { "Variable[\"dhb_minigame_upgrade_required\"] = false;\nVariable[\"dhb_minigame_upgrade_level\"] = 2", LuaTranslatorCode.GeneratedLuaCode279 },
            { "return Variable[\"dhb_minigame_upgrade_level\"] == 1", LuaTranslatorCode.GeneratedLuaCode280 },
            { "return Variable[\"dhb_minigame_upgrade_level\"] == 2", LuaTranslatorCode.GeneratedLuaCode281 },
            { "Variable[\"dhb_minigame_upgrade_required\"] = false;\nVariable[\"dhb_minigame_upgrade_level\"] = 3", LuaTranslatorCode.GeneratedLuaCode282 },
            { "return Variable[\"dhb_trance_stage\"] ~= \"Awake\"", LuaTranslatorCode.GeneratedLuaCode283 },
            { "return Variable[\"dhb_trance_stage\"] == \"Awake\"", LuaTranslatorCode.GeneratedLuaCode284 },
            { "Variable[\"dbh_voodoo_station_unlocked\"] = true", LuaTranslatorCode.GeneratedLuaCode285 },
            { "return not (Variable[\"dhb_minigame_completed\"] or Variable[\"dbh_voodoo_station_unlocked\"] ) and Variable[\"dhb_took_mortar_and_pestle\"]", LuaTranslatorCode.GeneratedLuaCode286 },
            { "Variable[\"dhb_met_ricky\"] = true;\nexit_after_mint = false;", LuaTranslatorCode.GeneratedLuaCode287 },
            { "return Variable[\"global_act_1_quest_stage\"] ~= \"VDWasBombed\"", LuaTranslatorCode.GeneratedLuaCode288 },
            { "return Variable[\"mansion_met_victor\"]", LuaTranslatorCode.GeneratedLuaCode289 },
            { "Variable[\"dhb_asked_ricky_about_benny\"] = true;", LuaTranslatorCode.GeneratedLuaCode290 },
            { "return Variable[\"mansion_met_benny\"]", LuaTranslatorCode.GeneratedLuaCode291 },
            { "return Variable[\"chic_met_kiki\"] or Variable[\"mansion_learned_of_kiki\"]", LuaTranslatorCode.GeneratedLuaCode292 },
            { "return Variable[\"cc_met_gordon\"] or Variable[\"dhb_ricky_mentioned_victor_and_gordon\"] or Variable[\"mansion_argument_finished\"]", LuaTranslatorCode.GeneratedLuaCode293 },
            { "return not Variable[\"dhb_took_mortar_and_pestle\"]", LuaTranslatorCode.GeneratedLuaCode294 },
            { "return Variable[\"dhb_ricky_offered_mortar_for_mint\"]", LuaTranslatorCode.GeneratedLuaCode295 },
            { "Variable[\"dhb_ricky_offered_mortar_for_mint\"] = true;", LuaTranslatorCode.GeneratedLuaCode296 },
            { "return not Variable[\"dhb_ricky_offered_mortar_for_mint\"]", LuaTranslatorCode.GeneratedLuaCode297 },
            { "return InventoryContains(\"Mint\")", LuaTranslatorCode.GeneratedLuaCode298 },
            { "Variable[\"dhb_took_mortar_and_pestle\"] = true;", LuaTranslatorCode.GeneratedLuaCode299 },
            { "return not InventoryContains(\"Mint\")", LuaTranslatorCode.GeneratedLuaCode300 },
            { "return Variable[\"dhb_drink_count\"] > 0", LuaTranslatorCode.GeneratedLuaCode301 },
            { "return Variable[\"dhb_drink_count\"] <= 0", LuaTranslatorCode.GeneratedLuaCode302 },
            { "return Variable[\"dhb_drink_count\"] == 3", LuaTranslatorCode.GeneratedLuaCode303 },
            { "return Variable[\"dhb_drink_count\"] < 3", LuaTranslatorCode.GeneratedLuaCode304 },
            { "Variable[\"dhb_ricky_mentioned_victor_and_gordon\"] = true", LuaTranslatorCode.GeneratedLuaCode305 },
            { "return not (InventoryContains(\"Ricky's Letter\") or Variable[\"mansion_greenhouse_unlocked\"])", LuaTranslatorCode.GeneratedLuaCode306 },
            { "return not Variable[\"mansion_greenhouse_unlocked\"] and InventoryContains(\"Ricky's Letter\")", LuaTranslatorCode.GeneratedLuaCode307 },
            { "return Variable[\"mansion_greenhouse_unlocked\"]", LuaTranslatorCode.GeneratedLuaCode308 },
            { "Variable[\"dhb_mentioned_hounfo\"] = true;", LuaTranslatorCode.GeneratedLuaCode309 },
            { "return  Variable[\"global_act_1_quest_stage\"] == \"FindPendantOwner\"", LuaTranslatorCode.GeneratedLuaCode310 },
            { "Variable[\"dhb_visited_post_bombing\"] = true;", LuaTranslatorCode.GeneratedLuaCode311 },
            { "Variable[\"dhb_drink_count\"] = Variable[\"dhb_drink_count\"] - 1;", LuaTranslatorCode.GeneratedLuaCode312 },
            { "return Variable[\"dhb_drink_count\"] <= 1", LuaTranslatorCode.GeneratedLuaCode313 },
            { "return InventoryContains(\"Tear Stained Letter\")", LuaTranslatorCode.GeneratedLuaCode314 },
            { "return not InventoryContains(\"Tear Stained Letter\")", LuaTranslatorCode.GeneratedLuaCode315 },
            { "return Variable[\"dhb_drink_count\"] > 1", LuaTranslatorCode.GeneratedLuaCode316 },
            { "return exit_after_mint", LuaTranslatorCode.GeneratedLuaCode317 },
            { "return not exit_after_mint", LuaTranslatorCode.GeneratedLuaCode318 },
            { "Variable[\"dhb_trance_stage\"] = \"Wet\"", LuaTranslatorCode.GeneratedLuaCode319 },
            { "Variable[\"dhb_trance_stage\"] = \"Hurt\";\nInventoryRemoveItem(\"Chair\");", LuaTranslatorCode.GeneratedLuaCode320 },
            { "Variable[\"dhb_trance_stage\"] = \"Awake\"", LuaTranslatorCode.GeneratedLuaCode321 },
            { "Variable[\"dhb_trance_stage\"] = \"Slapped\";\nInventoryRemoveItem(\"Metal Gauntlet\");", LuaTranslatorCode.GeneratedLuaCode322 },
            { "exit_after_mint = true;", LuaTranslatorCode.GeneratedLuaCode323 },
            { "return InventoryContains(\"Bucket of Water\")", LuaTranslatorCode.GeneratedLuaCode324 },
            { "return not InventoryContains(\"Bucket of Water\")", LuaTranslatorCode.GeneratedLuaCode325 },
            { "return Variable[\"dhb_trance_stage\"] == \"Wet\"", LuaTranslatorCode.GeneratedLuaCode326 },
            { "return Variable[\"dhb_trance_stage\"] ~= \"Wet\"", LuaTranslatorCode.GeneratedLuaCode327 },
            { "return InventoryContains(\"Chair\")", LuaTranslatorCode.GeneratedLuaCode328 },
            { "return not InventoryContains(\"Chair\")", LuaTranslatorCode.GeneratedLuaCode329 },
            { "return Variable[\"dhb_trance_stage\"] == \"Hurt\"", LuaTranslatorCode.GeneratedLuaCode330 },
            { "return Variable[\"dhb_trance_stage\"] ~= \"Hurt\"", LuaTranslatorCode.GeneratedLuaCode331 },
            { "return Variable[\"dhb_met_ricky\"]", LuaTranslatorCode.GeneratedLuaCode332 },
            { "return not Variable[\"dhb_met_ricky\"]", LuaTranslatorCode.GeneratedLuaCode333 },
            { "return not Variable[\"dbh_voodoo_station_unlocked\"]", LuaTranslatorCode.GeneratedLuaCode334 },
            { "return Variable[\"dbh_voodoo_station_unlocked\"]", LuaTranslatorCode.GeneratedLuaCode335 },
            { "Variable[\"if_finished_possession\"] = true;\nInventoryRemoveItem(\"Ason\");", LuaTranslatorCode.GeneratedLuaCode336 },
            { "return Variable[\"if_drew_veve\"] and Variable[\"if_ason_complete\"]", LuaTranslatorCode.GeneratedLuaCode337 },
            { "return not (Variable[\"if_drew_veve\"] and Variable[\"if_ason_complete\"])", LuaTranslatorCode.GeneratedLuaCode338 },
            { "return not Variable[\"if_drew_veve\"]", LuaTranslatorCode.GeneratedLuaCode339 },
            { "return InventoryContains(\"Broken Ason\")", LuaTranslatorCode.GeneratedLuaCode340 },
            { "return not InventoryContains(\"Broken Ason\")", LuaTranslatorCode.GeneratedLuaCode341 },
            { "return Variable[\"if_drew_veve\"]", LuaTranslatorCode.GeneratedLuaCode342 },
            { "Variable[\"if_drew_veve\"] = true;", LuaTranslatorCode.GeneratedLuaCode343 },
            { "return not Variable[\"if_francois_explained_death\"]", LuaTranslatorCode.GeneratedLuaCode344 },
            { "return Variable[\"if_francois_explained_death\"]", LuaTranslatorCode.GeneratedLuaCode345 },
            { "Variable[\"if_acquired_teeth\"] = true;", LuaTranslatorCode.GeneratedLuaCode346 },
            { "return not Variable[\"if_acquired_teeth\"]", LuaTranslatorCode.GeneratedLuaCode347 },
            { "return Variable[\"if_acquired_teeth\"]", LuaTranslatorCode.GeneratedLuaCode348 },
            { "return Variable[\"if_met_francois\"]", LuaTranslatorCode.GeneratedLuaCode349 },
            { "Variable[\"if_francois_recognized_mary\"] = true", LuaTranslatorCode.GeneratedLuaCode350 },
            { "Variable[\"if_met_francois\"] = true", LuaTranslatorCode.GeneratedLuaCode351 },
            { "return not Variable[\"if_met_francois\"]", LuaTranslatorCode.GeneratedLuaCode352 },
            { "return not Variable[\"if_lake_drained\"]", LuaTranslatorCode.GeneratedLuaCode353 },
            { "return Variable[\"if_lake_drained\"]", LuaTranslatorCode.GeneratedLuaCode354 },
            { "return not Variable[\"if_francois_recognized_mary\"]", LuaTranslatorCode.GeneratedLuaCode355 },
            { "return Variable[\"if_francois_recognized_mary\"]", LuaTranslatorCode.GeneratedLuaCode356 },
            { "Variable[\"if_francois_told_long_story\"] = true;", LuaTranslatorCode.GeneratedLuaCode357 },
            { "Variable[\"if_francois_gave_quest\"] = true;", LuaTranslatorCode.GeneratedLuaCode358 },
            { "return Variable[\"if_francois_told_long_story\"]", LuaTranslatorCode.GeneratedLuaCode359 },
            { "return not InventoryContains(\"Sign of Papa Legba\")", LuaTranslatorCode.GeneratedLuaCode360 },
            { "Variable[\"if_francois_explained_death\"] = true", LuaTranslatorCode.GeneratedLuaCode361 },
            { "Variable[\"if_francois_lied\"] = true;", LuaTranslatorCode.GeneratedLuaCode362 },
            { "return InventoryContains(\"Sign of Papa Legba\")", LuaTranslatorCode.GeneratedLuaCode363 },
            { "Variable[\"if_can_touch_francois_stuff\"] = true", LuaTranslatorCode.GeneratedLuaCode364 },
            { "Variable[\"if_pot_contains_pyrite\"] = true;", LuaTranslatorCode.GeneratedLuaCode365 },
            { "Variable[\"if_acquired_charcoal\"] = true;", LuaTranslatorCode.GeneratedLuaCode366 },
            { "return not Variable[\"if_acquired_charcoal\"]", LuaTranslatorCode.GeneratedLuaCode367 },
            { "return Variable[\"if_acquired_charcoal\"]", LuaTranslatorCode.GeneratedLuaCode368 },
            { "Variable[\"if_cupboard_open\"] = true", LuaTranslatorCode.GeneratedLuaCode369 },
            { "return not Variable[\"if_cupboard_open\"]", LuaTranslatorCode.GeneratedLuaCode370 },
            { "return Variable[\"if_cupboard_open\"]", LuaTranslatorCode.GeneratedLuaCode371 },
            { "Variable[\"if_acquired_cereal\"] = true;", LuaTranslatorCode.GeneratedLuaCode372 },
            { "return not Variable[\"if_acquired_cereal\"]", LuaTranslatorCode.GeneratedLuaCode373 },
            { "return Variable[\"if_acquired_cereal\"]", LuaTranslatorCode.GeneratedLuaCode374 },
            { "return not Variable[\"if_pot_contains_pyrite\"]", LuaTranslatorCode.GeneratedLuaCode375 },
            { "return not Variable[\"if_stove_on\"]", LuaTranslatorCode.GeneratedLuaCode376 },
            { "return Variable[\"if_stove_on\"]", LuaTranslatorCode.GeneratedLuaCode377 },
            { "return Variable[\"if_pot_contains_pyrite\"]", LuaTranslatorCode.GeneratedLuaCode378 },
            { "Variable[\"if_stove_on\"] = true;", LuaTranslatorCode.GeneratedLuaCode379 },
            { "return Variable[\"if_stove_on\"] and Variable[\"if_pot_contains_pyrite\"]", LuaTranslatorCode.GeneratedLuaCode380 },
            { "return not (Variable[\"if_stove_on\"] and Variable[\"if_pot_contains_pyrite\"])", LuaTranslatorCode.GeneratedLuaCode381 },
            { "Variable[\"if_acquired_sulfur\"] = true;", LuaTranslatorCode.GeneratedLuaCode382 },
            { "return not Variable[\"if_acquired_sulfur\"]", LuaTranslatorCode.GeneratedLuaCode383 },
            { "return Variable[\"if_acquired_sulfur\"]", LuaTranslatorCode.GeneratedLuaCode384 },
            { "Variable[\"if_washed_up\"] = true;", LuaTranslatorCode.GeneratedLuaCode385 },
            { "Variable[\"if_acquired_feather\"] = true;\nInventoryRemoveItem(\"Kooka Bunches Cereal\");", LuaTranslatorCode.GeneratedLuaCode386 },
            { "return Variable[\"if_bird_scared\"]", LuaTranslatorCode.GeneratedLuaCode387 },
            { "return not Variable[\"if_bird_scared\"]", LuaTranslatorCode.GeneratedLuaCode388 },
            { "Variable[\"if_lake_drained\"] = true;\nInventoryRemoveItem(\"Blasting Plunger\");\nVariable[\"global_act_2_quest_stage\"] = \"HandleTheHounfo\";", LuaTranslatorCode.GeneratedLuaCode389 },
            { "return not Variable[\"if_acquired_guano\"]", LuaTranslatorCode.GeneratedLuaCode390 },
            { "return Variable[\"if_acquired_guano\"]", LuaTranslatorCode.GeneratedLuaCode391 },
            { "Variable[\"if_acquired_guano\"] = true;", LuaTranslatorCode.GeneratedLuaCode392 },
            { "return Variable[\"yacht_drink_count\"] <= 0", LuaTranslatorCode.GeneratedLuaCode393 },
            { "return not Variable[\"yacht_swallowed_toilet_handle\"] or Variable[\"yacht_acquired_toilet_handle\"]", LuaTranslatorCode.GeneratedLuaCode394 },
            { "return SceneName() ~= \"Middle Deck (Exquisite Bathroom)\"", LuaTranslatorCode.GeneratedLuaCode395 },
            { "return SceneName() == \"Middle Deck (Exquisite Bathroom)\"", LuaTranslatorCode.GeneratedLuaCode396 },
            { "Variable[\"yacht_acquired_toilet_handle\"] = true;", LuaTranslatorCode.GeneratedLuaCode397 },
            { "return Variable[\"yacht_swallowed_toilet_handle\"]", LuaTranslatorCode.GeneratedLuaCode398 },
            { "Variable[\"yacht_drink_count\"] = Variable[\"yacht_drink_count\"] - 1", LuaTranslatorCode.GeneratedLuaCode399 },
            { "return Variable[\"yacht_drink_count\"] > 0", LuaTranslatorCode.GeneratedLuaCode400 },
            { "return not Variable[\"yacht_acquired_toilet_handle\"] and Variable[\"yacht_swallowed_toilet_handle\"]", LuaTranslatorCode.GeneratedLuaCode401 },
            { "return not Variable[\"yacht_swallowed_toilet_handle\"]", LuaTranslatorCode.GeneratedLuaCode402 },
            { "Variable[\"factory_drank_stimulant\"] = true;", LuaTranslatorCode.GeneratedLuaCode403 },
            { "Variable[\"yacht_swallowed_toilet_handle\"] = true;", LuaTranslatorCode.GeneratedLuaCode404 },
            { "return Variable[\"yacht_stall_closed\"] and Variable[\"yacht_vd_in_stall\"]", LuaTranslatorCode.GeneratedLuaCode405 },
            { "return not (Variable[\"yacht_stall_closed\"] and Variable[\"yacht_vd_in_stall\"])", LuaTranslatorCode.GeneratedLuaCode406 },
            { "Variable[\"office_mary_was_resurrected\"] = true;", LuaTranslatorCode.GeneratedLuaCode407 },
            { "Variable[\"global_portal_flag\"] = true;", LuaTranslatorCode.GeneratedLuaCode408 },
            { "return SceneName() ~= \"Papa Legba Realm (Sign Crossroads)\"", LuaTranslatorCode.GeneratedLuaCode409 },
            { "return not CanUseSignOfPapaLegba()", LuaTranslatorCode.GeneratedLuaCode410 },
            { "return CanUseSignOfPapaLegba()", LuaTranslatorCode.GeneratedLuaCode411 },
            { "return SceneName() == \"Papa Legba Realm (Sign Crossroads)\"", LuaTranslatorCode.GeneratedLuaCode412 },
            { "return SceneName() ~= \"Factory (Floor South)\"", LuaTranslatorCode.GeneratedLuaCode413 },
            { "return SceneName() == \"Factory (Floor South)\"", LuaTranslatorCode.GeneratedLuaCode414 },
            { "return not InventoryContains(\"Baron Samedi Essence\")", LuaTranslatorCode.GeneratedLuaCode415 },
            { "return InventoryContains(\"Baron Samedi Essence\")", LuaTranslatorCode.GeneratedLuaCode416 },
            { "Variable[\"global_act_3_quest_stage\"] = \"StopVictor\";", LuaTranslatorCode.GeneratedLuaCode417 },
            { "InventoryRemoveItem(\"Cored Apple\");\nInventoryAddItem(\"Apple of my Eye\");", LuaTranslatorCode.GeneratedLuaCode418 },
            { "InventoryRemoveItem(\"Autograph\");\nVariable[\"yacht_apple_autographed\"] = true;", LuaTranslatorCode.GeneratedLuaCode419 },
            { "return Variable[\"yacht_apple_syruped\"] and Variable[\"yacht_apple_autographed\"]", LuaTranslatorCode.GeneratedLuaCode420 },
            { "InventoryRemoveItem(\"Simple Syrup\");\nVariable[\"yacht_apple_syruped\"] = true;", LuaTranslatorCode.GeneratedLuaCode421 },
            { "InventoryRemoveItem(\"Apple of my Eye\");\nInventoryRemoveItem(\"Knife\");\nInventoryAddItem(\"Apple of my Eye (Left)\");\nInventoryAddItem(\"Apple of my Eye (Right)\");", LuaTranslatorCode.GeneratedLuaCode422 },
            { "InventoryAddItem(\"Fire\");\nInventoryRemoveItem(\"Gum Wrapper\");\nInventoryRemoveItem(\"Battery\");", LuaTranslatorCode.GeneratedLuaCode423 },
            { "InventoryAddItem(\"Molotov Cocktail (Lit)\");\nInventoryRemoveItem(\"Molotov Cocktail\");\nInventoryRemoveItem(\"Fire\");", LuaTranslatorCode.GeneratedLuaCode424 },
            { "InventoryAddItem(\"Molotov Cocktail\");\nInventoryRemoveItem(\"Aged Rum\");\nInventoryRemoveItem(\"Washcloth\");", LuaTranslatorCode.GeneratedLuaCode425 },
            { "InventoryRemoveItem(\"Bat Guano\");\nInventoryRemoveItem(\"Metal Cup\");\nInventoryAddItem(\"Metal Cup (Mixture)\");\nVariable[\"if_combined_bat_guano\"] = true;", LuaTranslatorCode.GeneratedLuaCode426 },
            { "return Variable[\"if_combined_charcoal\"] and Variable[\"if_combined_bat_guano\"] and Variable[\"if_combined_sulfur\"]", LuaTranslatorCode.GeneratedLuaCode427 },
            { "Variable[\"if_combined_charcoal\"] = true;", LuaTranslatorCode.GeneratedLuaCode428 },
            { "InventoryRemoveItem(\"Charcoal\");\nInventoryRemoveItem(\"Metal Cup\");\nInventoryAddItem(\"Metal Cup (Mixture)\");", LuaTranslatorCode.GeneratedLuaCode429 },
            { "InventoryAddItem(\"Grammy's Flamin' Hot Sauce\");\nInventoryRemoveItem(\"Metal Cup (Mixture)\");", LuaTranslatorCode.GeneratedLuaCode430 },
            { "InventoryRemoveItem(\"Sulfur\");\nInventoryRemoveItem(\"Metal Cup\");\nInventoryAddItem(\"Metal Cup (Mixture)\");\nVariable[\"if_combined_sulfur\"] = true;", LuaTranslatorCode.GeneratedLuaCode431 },
            { "InventoryRemoveItem(\"Teeth\");\nInventoryRemoveItem(\"Broken Ason\");\nInventoryAddItem(\"Ason\");\nVariable[\"if_ason_complete\"] = true;", LuaTranslatorCode.GeneratedLuaCode432 },
            { "Variable[\"owner_honer_ingredient_black_candle\"] = true;\nInventoryRemoveItem(\"Black Candle\");\nInventoryRemoveItem(\"Mortar and Pestle\");\nInventoryAddItem(\"Mortar and Pestle (Mixture)\");", LuaTranslatorCode.GeneratedLuaCode433 },
            { "return Variable[\"owner_honer_ingredient_magnet\"] and Variable[\"owner_honer_ingredient_lemon\"] and Variable[\"owner_honer_ingredient_black_candle\"]", LuaTranslatorCode.GeneratedLuaCode434 },
            { "InventoryRemoveItem(\"Lemon\");\nInventoryRemoveItem(\"Mortar and Pestle\");\nInventoryAddItem(\"Mortar and Pestle (Mixture)\");\nVariable[\"owner_honer_ingredient_lemon\"] = true;", LuaTranslatorCode.GeneratedLuaCode435 },
            { "InventoryRemoveItem(\"Pendant\");\nInventoryRemoveItem(\"Owner Honer\");\nInventoryAddItem(\"Owner Honer Pendant\");\nVariable[\"owner_honer_active\"] = true;", LuaTranslatorCode.GeneratedLuaCode436 },
            { "InventoryRemoveItem(\"Permanent Magnet\");\nInventoryRemoveItem(\"Mortar and Pestle\");\nInventoryAddItem(\"Mortar and Pestle (Mixture)\");\nVariable[\"owner_honer_ingredient_magnet\"] = true;", LuaTranslatorCode.GeneratedLuaCode437 },
            { "InventoryAddItem(\"Permanent Magnet\");\nInventoryRemoveItem(\"Radio Speaker\");\nVariable[\"office_acquired_permanent_magnet\"] = true;", LuaTranslatorCode.GeneratedLuaCode438 },
            { "return Variable[\"ll_vent_is_open\"]", LuaTranslatorCode.GeneratedLuaCode439 },
            { "InventoryRemoveItem(\"Screwdriver\");", LuaTranslatorCode.GeneratedLuaCode440 },
            { "InventoryAddItem(\"Owner Honer\");\nInventoryRemoveItem(\"Mortar and Pestle (Mixture)\");", LuaTranslatorCode.GeneratedLuaCode441 },
            { "InventoryAddItem(\"Poisoned Chocolates\");\nInventoryRemoveItem(\"Fugo Fish Gland\");\nInventoryRemoveItem(\"Chocolates\");", LuaTranslatorCode.GeneratedLuaCode442 },
            { "InventoryAddItem(\"Coffee Cup (Spiked)\");\nInventoryRemoveItem(\"Coffee Cup (Full)\");\nInventoryRemoveItem(\"Centennial Dragon Heart Plumeria\");", LuaTranslatorCode.GeneratedLuaCode443 },
            { "return Variable[\"if_ason_complete\"]", LuaTranslatorCode.GeneratedLuaCode444 },
            { "return not Variable[\"if_ason_complete\"]", LuaTranslatorCode.GeneratedLuaCode445 },
            { "return not Variable[\"pl_mind_numb\"]", LuaTranslatorCode.GeneratedLuaCode446 },
            { "Variable[\"pl_mind_numb\"] = true", LuaTranslatorCode.GeneratedLuaCode447 },
            { "return Variable[\"pl_mind_numb\"]", LuaTranslatorCode.GeneratedLuaCode448 },
            { "return not (Variable[\"yacht_apple_syruped\"] or Variable[\"yacht_apple_autographed\"])", LuaTranslatorCode.GeneratedLuaCode449 },
            { "return Variable[\"yacht_apple_syruped\"]", LuaTranslatorCode.GeneratedLuaCode450 },
            { "return Variable[\"yacht_apple_autographed\"]", LuaTranslatorCode.GeneratedLuaCode451 },
            { "return not Variable[\"yacht_acquired_toilet_handle\"]", LuaTranslatorCode.GeneratedLuaCode452 },
            { "return Variable[\"yacht_acquired_toilet_handle\"]", LuaTranslatorCode.GeneratedLuaCode453 },
            { "return not (Variable[\"if_combined_charcoal\"] or Variable[\"if_combined_bat_guano\"] or Variable[\"if_combined_sulfur\"])", LuaTranslatorCode.GeneratedLuaCode454 },
            { "return not (Variable[\"if_combined_charcoal\"] or Variable[\"if_combined_bat_guano\"]) and Variable[\"if_combined_sulfur\"]", LuaTranslatorCode.GeneratedLuaCode455 },
            { "return not (Variable[\"if_combined_charcoal\"] or Variable[\"if_combined_sulfur\"]) and Variable[\"if_combined_bat_guano\"]", LuaTranslatorCode.GeneratedLuaCode456 },
            { "return not (Variable[\"if_combined_bat_guano\"] or Variable[\"if_combined_sulfur\"]) and Variable[\"if_combined_charcoal\"]", LuaTranslatorCode.GeneratedLuaCode457 },
            { "return not Variable[\"if_combined_bat_guano\"] and Variable[\"if_combined_sulfur\"] and Variable[\"if_combined_charcoal\"]", LuaTranslatorCode.GeneratedLuaCode458 },
            { "return not Variable[\"if_combined_sulfur\"] and Variable[\"if_combined_bat_guano\"] and Variable[\"if_combined_charcoal\"]", LuaTranslatorCode.GeneratedLuaCode459 },
            { "return not Variable[\"if_combined_charcoal\"] and Variable[\"if_combined_bat_guano\"] and Variable[\"if_combined_sulfur\"]", LuaTranslatorCode.GeneratedLuaCode460 },
            { "return not (Variable[\"owner_honer_ingredient_magnet\"] and Variable[\"owner_honer_ingredient_lemon\"] and Variable[\"owner_honer_ingredient_black_candle\"])", LuaTranslatorCode.GeneratedLuaCode461 },
            { "using_desk = false;\n", LuaTranslatorCode.GeneratedLuaCode462 },
            { "return using_desk", LuaTranslatorCode.GeneratedLuaCode463 },
            { "x = RandomChoice(\"Talk to Shopkeeper\",3);", LuaTranslatorCode.GeneratedLuaCode464 },
            { "return not (Variable[\"cc_gordon_is_poisoned\"] or InventoryContains(\"Chocolates\")) and Variable[\"cc_gordon_mentioned_chocolates\"]", LuaTranslatorCode.GeneratedLuaCode465 },
            { "return CanAfford(3)", LuaTranslatorCode.GeneratedLuaCode466 },
            { "return Variable[\"mansion_victor_helped_with_shovel\"]", LuaTranslatorCode.GeneratedLuaCode467 },
            { "return CanAfford(15)", LuaTranslatorCode.GeneratedLuaCode468 },
            { "Variable[\"it_need_victor_for_shovel\"] = true;", LuaTranslatorCode.GeneratedLuaCode469 },
            { "return not (Variable[\"cemetery_gave_eartha_shovel\"] or InventoryContains(\"Shovel\")) and Variable[\"cemetery_eartha_wants_shovel\"]", LuaTranslatorCode.GeneratedLuaCode470 },
            { "return not Variable[\"mansion_victor_helped_with_shovel\"]", LuaTranslatorCode.GeneratedLuaCode471 },
            { "return Variable[\"it_clicked_shirts\"]", LuaTranslatorCode.GeneratedLuaCode472 },
            { "Variable[\"it_clicked_shirts\"] = true;", LuaTranslatorCode.GeneratedLuaCode473 },
            { "return not Variable[\"it_clicked_shirts\"]", LuaTranslatorCode.GeneratedLuaCode474 },
            { "x = RandomChoice(\"Island Trader Shirt Rack\",5);", LuaTranslatorCode.GeneratedLuaCode475 },
            { "Variable[\"it_acquired_camera\"] = true;", LuaTranslatorCode.GeneratedLuaCode476 },
            { "return CanAfford(10)", LuaTranslatorCode.GeneratedLuaCode477 },
            { "return not Variable[\"it_acquired_camera\"]", LuaTranslatorCode.GeneratedLuaCode478 },
            { "return Variable[\"it_acquired_camera\"]", LuaTranslatorCode.GeneratedLuaCode479 },
            { "return CanAfford(2)", LuaTranslatorCode.GeneratedLuaCode480 },
            { "Variable[\"ll_photos_taken\"] = true;", LuaTranslatorCode.GeneratedLuaCode481 },
            { "Variable[\"ll_refused_to_talk\"] = true", LuaTranslatorCode.GeneratedLuaCode482 },
            { "return not Variable[\"ll_gave_theodore_photos\"]", LuaTranslatorCode.GeneratedLuaCode483 },
            { "return Variable[\"global_act_1_quest_stage\"] == \"FindPendantOwner\" ", LuaTranslatorCode.GeneratedLuaCode484 },
            { "Variable[\"ll_gave_theodore_photos\"] = true;\nVariable[\"global_act_1_quest_stage\"] = \"AcquireJournal\";", LuaTranslatorCode.GeneratedLuaCode485 },
            { "Variable[\"ll_cabinet_open\"] = true;", LuaTranslatorCode.GeneratedLuaCode486 },
            { "Variable[\"global_act_1_quest_stage\"] = \"AcquireJournal\";", LuaTranslatorCode.GeneratedLuaCode487 },
            { "return InventoryContains(\"LeMoon Bank Account Receipt\")", LuaTranslatorCode.GeneratedLuaCode488 },
            { "return not InventoryContains(\"LeMoon Bank Account Receipt\")", LuaTranslatorCode.GeneratedLuaCode489 },
            { "Variable[\"ll_is_stake_out\"] = false;", LuaTranslatorCode.GeneratedLuaCode490 },
            { "Variable[\"ll_vent_is_open\"] = true;", LuaTranslatorCode.GeneratedLuaCode491 },
            { "return Variable[\"office_acquired_permanent_magnet\"]", LuaTranslatorCode.GeneratedLuaCode492 },
            { "Variable[\"ll_cant_fit_in_shaft\"] = true;", LuaTranslatorCode.GeneratedLuaCode493 },
            { "return not Variable[\"dhb_mentioned_hounfo\"]", LuaTranslatorCode.GeneratedLuaCode494 },
            { "return Variable[\"dhb_mentioned_hounfo\"]", LuaTranslatorCode.GeneratedLuaCode495 },
            { "Variable[\"mansion_saw_hoodoo_book\"] = true;", LuaTranslatorCode.GeneratedLuaCode496 },
            { "return Variable[\"mansion_bennys_drawer_open\"]", LuaTranslatorCode.GeneratedLuaCode497 },
            { "Variable[\"mansion_bennys_drawer_open\"] = true", LuaTranslatorCode.GeneratedLuaCode498 },
            { "return not Variable[\"mansion_bennys_drawer_open\"]", LuaTranslatorCode.GeneratedLuaCode499 },
            { "using_desk = true;", LuaTranslatorCode.GeneratedLuaCode500 },
            { "Variable[\"mansion_gained_entry\"] = true;", LuaTranslatorCode.GeneratedLuaCode501 },
            { "Variable[\"mansion_argument_finished\"] = true;", LuaTranslatorCode.GeneratedLuaCode502 },
            { "Variable[\"mansion_delivered_ricky_letter\"] = true;", LuaTranslatorCode.GeneratedLuaCode503 },
            { "return InventoryContains(\"Ricky's Letter\")", LuaTranslatorCode.GeneratedLuaCode504 },
            { "return not (InventoryContains(\"Greenhouse Key\") or Variable[\"mansion_greenhouse_unlocked\"]) and Variable[\"mansion_greenhouse_attempted\"]", LuaTranslatorCode.GeneratedLuaCode505 },
            { "return not Variable[\"mansion_delivered_ricky_letter\"]", LuaTranslatorCode.GeneratedLuaCode506 },
            { "return Variable[\"mansion_delivered_ricky_letter\"]", LuaTranslatorCode.GeneratedLuaCode507 },
            { "return not Variable[\"mansion_met_victor\"]", LuaTranslatorCode.GeneratedLuaCode508 },
            { "return Variable[\"mansion_saw_hoodoo_book\"]", LuaTranslatorCode.GeneratedLuaCode509 },
            { "return not Variable[\"mansion_saw_hoodoo_book\"]", LuaTranslatorCode.GeneratedLuaCode510 },
            { "Variable[\"mansion_greenhouse_unlocked\"] = true;", LuaTranslatorCode.GeneratedLuaCode511 },
            { "return InventoryContains(\"Greenhouse Key\")", LuaTranslatorCode.GeneratedLuaCode512 },
            { "Variable[\"mansion_greenhouse_attempted\"] = true;", LuaTranslatorCode.GeneratedLuaCode513 },
            { "return not InventoryContains(\"Greenhouse Key\")", LuaTranslatorCode.GeneratedLuaCode514 },
            { "return not Variable[\"mansion_met_benny\"]", LuaTranslatorCode.GeneratedLuaCode515 },
            { "Variable[\"mansion_met_benny\"] = true", LuaTranslatorCode.GeneratedLuaCode516 },
            { "Variable[\"global_act_1_quest_stage\"] = \"BombDeployed\"", LuaTranslatorCode.GeneratedLuaCode517 },
            { "return not Variable[\"mansion_took_mint\"]", LuaTranslatorCode.GeneratedLuaCode518 },
            { "Variable[\"mansion_took_mint\"] = true;", LuaTranslatorCode.GeneratedLuaCode519 },
            { "return Variable[\"mansion_took_mint\"]", LuaTranslatorCode.GeneratedLuaCode520 },
            { "Variable[\"mansion_took_lemon\"] = true", LuaTranslatorCode.GeneratedLuaCode521 },
            { "return not Variable[\"mansion_took_lemon\"]", LuaTranslatorCode.GeneratedLuaCode522 },
            { "return Variable[\"mansion_took_lemon\"]", LuaTranslatorCode.GeneratedLuaCode523 },
            { "return InventoryContains(\"Lemon\")", LuaTranslatorCode.GeneratedLuaCode524 },
            { "return not InventoryContains(\"Lemon\")", LuaTranslatorCode.GeneratedLuaCode525 },
            { "Variable[\"mansion_met_victor\"] = true", LuaTranslatorCode.GeneratedLuaCode526 },
            { "return not Variable[\"mansion_told_lemoon_story\"]", LuaTranslatorCode.GeneratedLuaCode527 },
            { "Variable[\"mansion_learned_of_kiki\"] = true", LuaTranslatorCode.GeneratedLuaCode528 },
            { "SetDialogueMemory(77,28);\nSetDialogueMemory(77,75);\nVariable[\"mansion_told_lemoon_story\"] = true;", LuaTranslatorCode.GeneratedLuaCode529 },
            { "Variable[\"mansion_victor_blamed_gordon\"] = true", LuaTranslatorCode.GeneratedLuaCode530 },
            { "Variable[\"mansion_victor_helped_with_shovel\"] = true", LuaTranslatorCode.GeneratedLuaCode531 },
            { "return not Variable[\"mansion_victor_helped_with_shovel\"] and Variable[\"it_need_victor_for_shovel\"]", LuaTranslatorCode.GeneratedLuaCode532 },
            { "x = RandomChoice(\"Angry Patient\",6);", LuaTranslatorCode.GeneratedLuaCode533 },
            { "x = RandomChoice(\"Happy Patient\",5);", LuaTranslatorCode.GeneratedLuaCode534 },
            { "Variable[\"pl_pipe_state\"] = \"Acquired\";\nInventoryRemoveItem(\"Book of Tax Law\");", LuaTranslatorCode.GeneratedLuaCode535 },
            { "return Variable[\"pl_pipe_state\"] ~= \"Stolen\"", LuaTranslatorCode.GeneratedLuaCode536 },
            { "return Variable[\"pl_pipe_state\"] == \"Stolen\"", LuaTranslatorCode.GeneratedLuaCode537 },
            { "Variable[\"pl_have_visited\"] = true;", LuaTranslatorCode.GeneratedLuaCode538 },
            { "Variable[\"pl_cane_state\"] = \"Used\";", LuaTranslatorCode.GeneratedLuaCode539 },
            { "Variable[\"pl_pipe_state\"] = \"Used\";", LuaTranslatorCode.GeneratedLuaCode540 },
            { "Variable[\"pl_hat_state\"] = \"Used\"", LuaTranslatorCode.GeneratedLuaCode541 },
            { "return Variable[\"pl_cane_state\"] ~= \"Used\" and Variable[\"pl_hat_state\"] ~= \"Used\" and Variable[\"pl_pipe_state\"] ~= \"Used\"", LuaTranslatorCode.GeneratedLuaCode542 },
            { "return (Variable[\"pl_cane_state\"] == \"Used\" or Variable[\"pl_hat_state\"] == \"Used\" or Variable[\"pl_pipe_state\"] == \"Used\") and (Variable[\"pl_cane_state\"] ~= \"Used\" or Variable[\"pl_hat_state\"] ~= \"Used\" or Variable[\"pl_pipe_state\"] ~= \"Used\")", LuaTranslatorCode.GeneratedLuaCode543 },
            { "Variable[\"pl_cane_state\"] = \"Acquired\"", LuaTranslatorCode.GeneratedLuaCode544 },
            { "return Variable[\"pl_cane_state\"] ~= \"Stolen\"", LuaTranslatorCode.GeneratedLuaCode545 },
            { "return Variable[\"pl_cane_state\"] == \"Stolen\"", LuaTranslatorCode.GeneratedLuaCode546 },
            { "Variable[\"pl_west_gc_examined\"] = true", LuaTranslatorCode.GeneratedLuaCode547 },
            { "return not Variable[\"pl_west_gc_examined\"]", LuaTranslatorCode.GeneratedLuaCode548 },
            { "return Variable[\"pl_west_gc_examined\"]", LuaTranslatorCode.GeneratedLuaCode549 },
            { "Variable[\"pl_west_mf_examined\"] = true", LuaTranslatorCode.GeneratedLuaCode550 },
            { "return not Variable[\"pl_west_mf_examined\"]", LuaTranslatorCode.GeneratedLuaCode551 },
            { "return Variable[\"pl_west_mf_examined\"]", LuaTranslatorCode.GeneratedLuaCode552 },
            { "Variable[\"pl_west_tl_examined\"] = true", LuaTranslatorCode.GeneratedLuaCode553 },
            { "return not Variable[\"pl_west_tl_examined\"]", LuaTranslatorCode.GeneratedLuaCode554 },
            { "return Variable[\"pl_west_tl_examined\"]", LuaTranslatorCode.GeneratedLuaCode555 },
            { "Variable[\"pl_west_vd_examined\"] = true", LuaTranslatorCode.GeneratedLuaCode556 },
            { "return not Variable[\"pl_west_vd_examined\"]", LuaTranslatorCode.GeneratedLuaCode557 },
            { "return Variable[\"pl_west_vd_examined\"]", LuaTranslatorCode.GeneratedLuaCode558 },
            { "return Variable[\"pl_statue_room_state\"] ~= Variable[\"pl_statue_room_success_state\"]", LuaTranslatorCode.GeneratedLuaCode559 },
            { "return Variable[\"pl_statue_room_state\"] == Variable[\"pl_statue_room_success_state\"]", LuaTranslatorCode.GeneratedLuaCode560 },
            { "Variable[\"pl_hat_state\"] = \"Acquired\"", LuaTranslatorCode.GeneratedLuaCode561 },
            { "return Variable[\"pl_hat_state\"] == \"Stolen\"", LuaTranslatorCode.GeneratedLuaCode562 },
            { "return Variable[\"pl_hat_state\"] ~= \"Stolen\"", LuaTranslatorCode.GeneratedLuaCode563 },
            { "Variable[\"pl_explained_arms\"] = true;", LuaTranslatorCode.GeneratedLuaCode564 },
            { "return not Variable[\"pl_explained_arms\"]", LuaTranslatorCode.GeneratedLuaCode565 },
            { "UnsetDialogueMemory(818, 2);\nUnsetDialogueMemory(818, 3);\nUnsetDialogueMemory(818, 6);", LuaTranslatorCode.GeneratedLuaCode566 },
            { "return Variable[\"pl_explained_arms\"]", LuaTranslatorCode.GeneratedLuaCode567 },
            { "Variable[\"global_current_act\"] = 3;", LuaTranslatorCode.GeneratedLuaCode568 },
            { "Variable[\"office_pl_needs_help\"] = true;", LuaTranslatorCode.GeneratedLuaCode569 },
            { "return Variable[\"office_pl_knows_mary\"]", LuaTranslatorCode.GeneratedLuaCode570 },
            { "Variable[\"office_pl_knows_mary\"] = true", LuaTranslatorCode.GeneratedLuaCode571 },
            { "return Variable[\"office_pl_needs_help\"]", LuaTranslatorCode.GeneratedLuaCode572 },
            { "InventoryAddItem(\"Sign of Papa Legba\")", LuaTranslatorCode.GeneratedLuaCode573 },
            { "Variable[\"global_act_2_quest_stage\"] = \"ReturnToBeach\";\nVariable[\"global_vd_outfit\"] = 2;", LuaTranslatorCode.GeneratedLuaCode574 },
            { "return not Variable[\"office_mary_was_resurrected\"]", LuaTranslatorCode.GeneratedLuaCode575 },
            { "return Variable[\"office_mary_was_resurrected\"]", LuaTranslatorCode.GeneratedLuaCode576 },
            { "return InventoryContains(\"Sign of Baron Samedi\");", LuaTranslatorCode.GeneratedLuaCode577 },
            { "Variable[\"office_ending_woke_up\"] = true;", LuaTranslatorCode.GeneratedLuaCode578 },
            { "Variable[\"office_title_flaming\"] = true", LuaTranslatorCode.GeneratedLuaCode579 },
            { "Variable[\"global_act_1_quest_stage\"] = \"Tutorial\"", LuaTranslatorCode.GeneratedLuaCode580 },
            { "x = RandomChoice(\"Knock on Office Door\",3);", LuaTranslatorCode.GeneratedLuaCode581 },
            { "Variable[\"office_donned_coat\"] = true;\nVariable[\"global_vd_outfit\"] = 2;", LuaTranslatorCode.GeneratedLuaCode582 },
            { "Variable[\"office_met_mary\"] = true;", LuaTranslatorCode.GeneratedLuaCode583 },
            { "return not InventoryContains(\"Pendant\") and Variable[\"office_mary_told_story\"]", LuaTranslatorCode.GeneratedLuaCode584 },
            { "Variable[\"office_mary_is_dreaming\"] = true;", LuaTranslatorCode.GeneratedLuaCode585 },
            { "Variable[\"office_refused_case_mary\"] = true;", LuaTranslatorCode.GeneratedLuaCode586 },
            { "Variable[\"office_mary_told_story\"] = true;\nSetDialogueMemory(110,112);", LuaTranslatorCode.GeneratedLuaCode587 },
            { "return not Variable[\"office_mary_told_story\"]", LuaTranslatorCode.GeneratedLuaCode588 },
            { "Variable[\"global_act_1_quest_stage\"] = \"FindPendantOwner\"", LuaTranslatorCode.GeneratedLuaCode589 },
            { "ChangeActorName(\"Mary Fontule\", \"New Client\");", LuaTranslatorCode.GeneratedLuaCode590 },
            { "Variable[\"office_mary_is_dreaming\"] = false;", LuaTranslatorCode.GeneratedLuaCode591 },
            { "return Variable[\"office_mary_told_story\"]", LuaTranslatorCode.GeneratedLuaCode592 },
            { "return InventoryContains(\"Pendant\") and Variable[\"office_met_mary\"]", LuaTranslatorCode.GeneratedLuaCode593 },
            { "Variable[\"office_radio_broken\"] = true;", LuaTranslatorCode.GeneratedLuaCode594 },
            { "return not Variable[\"office_radio_broken\"]", LuaTranslatorCode.GeneratedLuaCode595 },
            { "return Variable[\"office_radio_broken\"]", LuaTranslatorCode.GeneratedLuaCode596 },
            { "InventoryRemoveItem(\"Seltzer Bottle\"); \nVariable[\"office_title_flaming\"] = false; \nVariable[\"office_candle_extinguished\"] = true;\nVariable[\"global_act_1_quest_stage\"] = \"AnswerTelephone\"", LuaTranslatorCode.GeneratedLuaCode597 },
            { "return Variable[\"office_acquired_seltzer\"]", LuaTranslatorCode.GeneratedLuaCode598 },
            { "Variable[\"office_acquired_seltzer\"] = true;", LuaTranslatorCode.GeneratedLuaCode599 },
            { "return not Variable[\"office_acquired_seltzer\"]", LuaTranslatorCode.GeneratedLuaCode600 },
            { "return Variable[\"global_act_3_quest_stage\"] ~= \"EndGame\"", LuaTranslatorCode.GeneratedLuaCode601 },
            { "return Variable[\"global_current_act\"] == 2", LuaTranslatorCode.GeneratedLuaCode602 },
            { "Variable[\"global_act_1_quest_stage\"] = \"VDWasBombed\"", LuaTranslatorCode.GeneratedLuaCode603 },
            { "Variable[\"office_hidden_button_location\"] = \"Baron Samedi\"", LuaTranslatorCode.GeneratedLuaCode604 },
            { "return Variable[\"office_hidden_button_location\"] == \"Baron Samedi Selected\"", LuaTranslatorCode.GeneratedLuaCode605 },
            { "return not Variable[\"office_met_mary\"]", LuaTranslatorCode.GeneratedLuaCode606 },
            { "return Variable[\"office_met_mary\"]", LuaTranslatorCode.GeneratedLuaCode607 },
            { "Variable[\"office_hidden_button_location\"] = \"Papa Legba\"", LuaTranslatorCode.GeneratedLuaCode608 },
            { "return Variable[\"office_hidden_button_location\"] == \"Papa Legba Selected\"", LuaTranslatorCode.GeneratedLuaCode609 },
            { "return not Variable[\"office_fire_started\"]", LuaTranslatorCode.GeneratedLuaCode610 },
            { "return Variable[\"office_fire_started\"]", LuaTranslatorCode.GeneratedLuaCode611 },
            { "Variable[\"office_start_used_skull\"] = true;", LuaTranslatorCode.GeneratedLuaCode612 },
            { "return not Variable[\"office_start_used_skull\"]", LuaTranslatorCode.GeneratedLuaCode613 },
            { "Variable[\"office_message_played\"] = true", LuaTranslatorCode.GeneratedLuaCode614 },
            { "Variable[\"office_ending_used_skull\"] = true;", LuaTranslatorCode.GeneratedLuaCode615 },
            { "return not Variable[\"office_ending_used_skull\"] and Variable[\"global_act_3_quest_stage\"] == \"EndGame\"", LuaTranslatorCode.GeneratedLuaCode616 },
            { "return Variable[\"global_current_act\"] == 3 ", LuaTranslatorCode.GeneratedLuaCode617 },
            { "return Variable[\"global_act_3_quest_stage\"] ~= \"EndGame\" or Variable[\"office_ending_used_skull\"]", LuaTranslatorCode.GeneratedLuaCode618 },
            { "return Variable[\"office_start_used_skull\"]", LuaTranslatorCode.GeneratedLuaCode619 },
            { "return Variable[\"global_act_1_quest_stage\"] ~= \"AnswerTelephone\"", LuaTranslatorCode.GeneratedLuaCode620 },
            { "Variable[\"global_act_1_quest_stage\"] = \"Opening\"", LuaTranslatorCode.GeneratedLuaCode621 },
            { "return IsPlayerTurn()", LuaTranslatorCode.GeneratedLuaCode622 },
            { "return not IsPlayerTurn()", LuaTranslatorCode.GeneratedLuaCode623 },
            { "return not AreCombatantsAlive()", LuaTranslatorCode.GeneratedLuaCode624 },
            { "TryResetStatus();\ndialogue_type = GetDialogueType();", LuaTranslatorCode.GeneratedLuaCode625 },
            { "return AreCombatantsAlive()", LuaTranslatorCode.GeneratedLuaCode626 },
            { "return VictorHealth() <= 0", LuaTranslatorCode.GeneratedLuaCode627 },
            { "return VoodooHealth() <= 0", LuaTranslatorCode.GeneratedLuaCode628 },
            { "x = RandomChoice(\"Battle Voodoo Taunt\",5);", LuaTranslatorCode.GeneratedLuaCode629 },
            { "return dialogue_type == \"Voodoo Taunt\"", LuaTranslatorCode.GeneratedLuaCode630 },
            { "x = RandomChoice(\"Battle Victor Confused\",3);", LuaTranslatorCode.GeneratedLuaCode631 },
            { "return dialogue_type == \"Victor Confused\"", LuaTranslatorCode.GeneratedLuaCode632 },
            { "x = RandomChoice(\"Battle Voodoo Blocking\",3);", LuaTranslatorCode.GeneratedLuaCode633 },
            { "return dialogue_type == \"Voodoo Blocking\"", LuaTranslatorCode.GeneratedLuaCode634 },
            { "x = RandomChoice(\"Battle Victor Blocking\",3);", LuaTranslatorCode.GeneratedLuaCode635 },
            { "return dialogue_type == \"Victor Blocking\"", LuaTranslatorCode.GeneratedLuaCode636 },
            { "x = RandomChoice(\"Battle Victor Taunt\",3);", LuaTranslatorCode.GeneratedLuaCode637 },
            { "return dialogue_type == \"Victor Taunt\"", LuaTranslatorCode.GeneratedLuaCode638 },
            { "return x == 7", LuaTranslatorCode.GeneratedLuaCode639 },
            { "Variable[\"global_act_3_quest_stage\"] = \"EndGame\";\nInventoryRemoveItem(\"Baron Samedi Essence\");\nInventoryRemoveItem(\"Halligan\");\nInventoryRemoveItem(\"Govi\");", LuaTranslatorCode.GeneratedLuaCode640 },
            { "victor_move = PickVictorMove()", LuaTranslatorCode.GeneratedLuaCode641 },
            { "return victor_move == \"Soul Food Salve\"", LuaTranslatorCode.GeneratedLuaCode642 },
            { "return victor_move == \"Hostile Takeover\"", LuaTranslatorCode.GeneratedLuaCode643 },
            { "x = RandomChoice(\"Battle Victor Compliment\",3);", LuaTranslatorCode.GeneratedLuaCode644 },
            { "return victor_move == \"Backhanded Compliment\"", LuaTranslatorCode.GeneratedLuaCode645 },
            { "return victor_move == \"Field of Honor\"", LuaTranslatorCode.GeneratedLuaCode646 },
            { "return victor_move == \"Gentleman's Cower\"", LuaTranslatorCode.GeneratedLuaCode647 },
            { "return victor_move == \"Reload\"", LuaTranslatorCode.GeneratedLuaCode648 },
            { "return VictorBecameConfused()", LuaTranslatorCode.GeneratedLuaCode649 },
            { "x = RandomChoice(\"Battle Voodoo Attack Ineffective\",3);", LuaTranslatorCode.GeneratedLuaCode650 },
            { "return not VictorBecameConfused()", LuaTranslatorCode.GeneratedLuaCode651 },
            { "return DidVictorsWeaknessChange()", LuaTranslatorCode.GeneratedLuaCode652 },
            { "return not DidVictorsWeaknessChange()", LuaTranslatorCode.GeneratedLuaCode653 },
            { "z = 0;", LuaTranslatorCode.GeneratedLuaCode654 },
            { "return VictorWeaknessAtIndex(z) == \"Apple of my Eye\"", LuaTranslatorCode.GeneratedLuaCode655 },
            { "return VictorWeaknessAtIndex(z) == \"Grammy's Flamin' Hot Sauce\"", LuaTranslatorCode.GeneratedLuaCode656 },
            { "return VictorWeaknessAtIndex(z) == \"Nine Tenths of the Lwa\"", LuaTranslatorCode.GeneratedLuaCode657 },
            { "return VictorWeaknessAtIndex(z) == \"Urn a Soul\"", LuaTranslatorCode.GeneratedLuaCode658 },
            { "return VictorWeaknessAtIndex(z) == \"Private Dick Kick\"", LuaTranslatorCode.GeneratedLuaCode659 },
            { "z = z + 1;", LuaTranslatorCode.GeneratedLuaCode660 },
            { "return z < VictorWeaknessCount()", LuaTranslatorCode.GeneratedLuaCode661 },
            { "return z >= VictorWeaknessCount()", LuaTranslatorCode.GeneratedLuaCode662 },
            { "Variable[\"uw_battle_started\"] = true;", LuaTranslatorCode.GeneratedLuaCode663 },
            { "return not InventoryContains(\"Coffee Cup\")", LuaTranslatorCode.GeneratedLuaCode664 },
            { "return InventoryContains(\"Coffee Cup\")", LuaTranslatorCode.GeneratedLuaCode665 },
            { "return Variable[\"factory_drank_stimulant\"]", LuaTranslatorCode.GeneratedLuaCode666 },
            { "return not Variable[\"factory_drank_stimulant\"]", LuaTranslatorCode.GeneratedLuaCode667 },
            { "return InventoryContains(\"Coffee Cup (Spiked)\") or InventoryContains(\"Coffee Cup (Full)\")", LuaTranslatorCode.GeneratedLuaCode668 },
            { "return not (InventoryContains(\"Coffee Cup (Spiked)\") or InventoryContains(\"Coffee Cup (Full)\"))", LuaTranslatorCode.GeneratedLuaCode669 },
            { "Variable[\"factory_have_washcloth\"] = true;", LuaTranslatorCode.GeneratedLuaCode670 },
            { "return not Variable[\"factory_have_washcloth\"]", LuaTranslatorCode.GeneratedLuaCode671 },
            { "return Variable[\"factory_have_washcloth\"]", LuaTranslatorCode.GeneratedLuaCode672 },
            { "Variable[\"factory_used_govi\"] = true;\nVariable[\"global_act_3_quest_stage\"] = \"OpenTheSafe\";", LuaTranslatorCode.GeneratedLuaCode673 },
            { "Variable[\"factory_exhaust_sabotaged\"] = true;", LuaTranslatorCode.GeneratedLuaCode674 },
            { "Variable[\"factory_victor_entered_room\"] = true;", LuaTranslatorCode.GeneratedLuaCode675 },
            { "Variable[\"factory_exhaust_room_manhole_open\"] = true;", LuaTranslatorCode.GeneratedLuaCode676 },
            { "return not Variable[\"factory_exhaust_room_manhole_open\"]", LuaTranslatorCode.GeneratedLuaCode677 },
            { "return Variable[\"factory_exhaust_room_manhole_open\"]", LuaTranslatorCode.GeneratedLuaCode678 },
            { "return not Variable[\"factory_exhaust_sabotaged\"]", LuaTranslatorCode.GeneratedLuaCode679 },
            { "UnsetDialogueMemory(597, 11);\nUnsetDialogueMemory(597, 12);\nUnsetDialogueMemory(597, 26);", LuaTranslatorCode.GeneratedLuaCode680 },
            { "UnsetDialogueMemory(597, 11);", LuaTranslatorCode.GeneratedLuaCode681 },
            { "UnsetDialogueMemory(597, 14);\nUnsetDialogueMemory(597, 27);\nUnsetDialogueMemory(597, 32);\nUnsetDialogueMemory(597, 26);", LuaTranslatorCode.GeneratedLuaCode682 },
            { "Variable[\"factory_crane_holding_barrel\"] = true;", LuaTranslatorCode.GeneratedLuaCode683 },
            { "return not Variable[\"factory_crane_holding_barrel\"]", LuaTranslatorCode.GeneratedLuaCode684 },
            { "Variable[\"factory_crane_holding_barrel\"] = false;", LuaTranslatorCode.GeneratedLuaCode685 },
            { "return Variable[\"factory_crane_holding_barrel\"]", LuaTranslatorCode.GeneratedLuaCode686 },
            { "return Variable[\"factory_exhaust_sabotaged\"]", LuaTranslatorCode.GeneratedLuaCode687 },
            { "UnsetDialogueMemory(597, 11);\nUnsetDialogueMemory(597, 18);\nUnsetDialogueMemory(597, 30);", LuaTranslatorCode.GeneratedLuaCode688 },
            { "UnsetDialogueMemory(597, 34);\nUnsetDialogueMemory(597, 15);\nUnsetDialogueMemory(597, 26);", LuaTranslatorCode.GeneratedLuaCode689 },
            { "return not Variable[\"factory_victor_entered_room\"]", LuaTranslatorCode.GeneratedLuaCode690 },
            { "return Variable[\"factory_victor_entered_room\"]", LuaTranslatorCode.GeneratedLuaCode691 },
            { "Variable[\"factory_fell_from_window\"] = true", LuaTranslatorCode.GeneratedLuaCode692 },
            { "Variable[\"factory_barrel_room_manhole_open\"] = true;", LuaTranslatorCode.GeneratedLuaCode693 },
            { "return not Variable[\"factory_barrel_room_manhole_open\"]", LuaTranslatorCode.GeneratedLuaCode694 },
            { "return Variable[\"factory_barrel_room_manhole_open\"]", LuaTranslatorCode.GeneratedLuaCode695 },
            { "x = RandomChoice(\"Victor's Machine Broken\",4);", LuaTranslatorCode.GeneratedLuaCode696 },
            { "return not Variable[\"factory_power_redistributed\"]", LuaTranslatorCode.GeneratedLuaCode697 },
            { "return not Variable[\"factory_machine_destroyed\"]", LuaTranslatorCode.GeneratedLuaCode698 },
            { "Variable[\"factory_machine_destroyed\"] = true;", LuaTranslatorCode.GeneratedLuaCode699 },
            { "return Variable[\"factory_power_redistributed\"]", LuaTranslatorCode.GeneratedLuaCode700 },
            { "return Variable[\"factory_machine_destroyed\"]", LuaTranslatorCode.GeneratedLuaCode701 },
            { "Variable[\"factory_halligan_acquired\"] = true;", LuaTranslatorCode.GeneratedLuaCode702 },
            { "return not Variable[\"factory_halligan_acquired\"]", LuaTranslatorCode.GeneratedLuaCode703 },
            { "return Variable[\"factory_halligan_acquired\"]", LuaTranslatorCode.GeneratedLuaCode704 },
            { "Variable[\"factory_power_redistributed\"] = (Variable[\"factory_juicer_powered_up\"] and Variable[\"factory_beacon_powered_up\"]);", LuaTranslatorCode.GeneratedLuaCode705 },
            { "Variable[\"factory_power_redistributed\"] = false;", LuaTranslatorCode.GeneratedLuaCode706 },
            { "Variable[\"factory_juicer_powered_up\"] = true;", LuaTranslatorCode.GeneratedLuaCode707 },
            { "return not Variable[\"factory_juicer_powered_up\"] and FactoryReservePower() > 0", LuaTranslatorCode.GeneratedLuaCode708 },
            { "return Variable[\"factory_juicer_powered_up\"] or FactoryReservePower() == 0", LuaTranslatorCode.GeneratedLuaCode709 },
            { "Variable[\"factory_juicer_powered_up\"] = false;", LuaTranslatorCode.GeneratedLuaCode710 },
            { "return Variable[\"factory_juicer_powered_up\"]", LuaTranslatorCode.GeneratedLuaCode711 },
            { "return not Variable[\"factory_juicer_powered_up\"]", LuaTranslatorCode.GeneratedLuaCode712 },
            { "Variable[\"factory_beacon_powered_up\"] = true;", LuaTranslatorCode.GeneratedLuaCode713 },
            { "return not Variable[\"factory_beacon_powered_up\"] and FactoryReservePower() > 0", LuaTranslatorCode.GeneratedLuaCode714 },
            { "return Variable[\"factory_beacon_powered_up\"] or FactoryReservePower() == 0", LuaTranslatorCode.GeneratedLuaCode715 },
            { "Variable[\"factory_beacon_powered_up\"] = false;", LuaTranslatorCode.GeneratedLuaCode716 },
            { "return Variable[\"factory_beacon_powered_up\"]", LuaTranslatorCode.GeneratedLuaCode717 },
            { "return not Variable[\"factory_beacon_powered_up\"]", LuaTranslatorCode.GeneratedLuaCode718 },
            { "return not Variable[\"factory_beacon_powered_up\"] ", LuaTranslatorCode.GeneratedLuaCode719 },
            { "return Variable[\"factory_beacon_powered_up\"] ", LuaTranslatorCode.GeneratedLuaCode720 },
            { "UnsetDialogueMemory(851,2);", LuaTranslatorCode.GeneratedLuaCode721 },
            { "UnsetDialogueMemory(851,3);", LuaTranslatorCode.GeneratedLuaCode722 },
            { "x = RandomChoice(\"Victor Enters Room\",5);", LuaTranslatorCode.GeneratedLuaCode723 },
            { "x = RandomChoice(\"Victor Loads Gun\",6);", LuaTranslatorCode.GeneratedLuaCode724 },
            { "x = RandomChoice(\"Victor Approaching\",6);", LuaTranslatorCode.GeneratedLuaCode725 },
            { "Variable[\"factory_cowering\"] = true;", LuaTranslatorCode.GeneratedLuaCode726 },
            { "InventoryRemoveItem(\"Diamond\");\nVariable[\"factory_window_cut\"] = true;", LuaTranslatorCode.GeneratedLuaCode727 },
            { "Variable[\"factory_cowering\"] = false;", LuaTranslatorCode.GeneratedLuaCode728 },
            { "Variable[\"factory_fire_started\"] = true;\nInventoryRemoveItem(\"Molotov Cocktail (Lit)\");", LuaTranslatorCode.GeneratedLuaCode729 },
            { "Variable[\"factory_painting_moved\"] = true", LuaTranslatorCode.GeneratedLuaCode730 },
            { "return not Variable[\"factory_painting_moved\"]", LuaTranslatorCode.GeneratedLuaCode731 },
            { "return Variable[\"factory_painting_moved\"]", LuaTranslatorCode.GeneratedLuaCode732 },
            { "return not Variable[\"factory_acquired_battery\"]", LuaTranslatorCode.GeneratedLuaCode733 },
            { "return Variable[\"factory_acquired_battery\"]", LuaTranslatorCode.GeneratedLuaCode734 },
            { "Variable[\"factory_acquired_battery\"] = true;", LuaTranslatorCode.GeneratedLuaCode735 },
            { "Variable[\"factory_safe_open\"] = true", LuaTranslatorCode.GeneratedLuaCode736 },
            { "return InventoryContains(\"Diamond\")", LuaTranslatorCode.GeneratedLuaCode737 },
            { "return not InventoryContains(\"Diamond\")", LuaTranslatorCode.GeneratedLuaCode738 },
            { "return not Variable[\"factory_cowering\"]", LuaTranslatorCode.GeneratedLuaCode739 },
            { "return Variable[\"factory_cowering\"]", LuaTranslatorCode.GeneratedLuaCode740 },
            { "Variable[\"factory_acquired_gum_wrapper\"] = true;", LuaTranslatorCode.GeneratedLuaCode741 },
            { "return Variable[\"factory_acquired_gum_wrapper\"]", LuaTranslatorCode.GeneratedLuaCode742 },
            { "return not Variable[\"factory_acquired_gum_wrapper\"]", LuaTranslatorCode.GeneratedLuaCode743 },
            { "return not Variable[\"factory_window_cut\"]", LuaTranslatorCode.GeneratedLuaCode744 },
            { "return Variable[\"factory_fire_started\"] ", LuaTranslatorCode.GeneratedLuaCode745 },
            { "return Variable[\"factory_window_cut\"]", LuaTranslatorCode.GeneratedLuaCode746 },
            { "Variable[\"global_act_3_quest_stage\"] = \"SaveBaronSamedi\";", LuaTranslatorCode.GeneratedLuaCode747 },
            { "Variable[\"factory_smelled_forest\"] = true", LuaTranslatorCode.GeneratedLuaCode748 },
            { "Variable[\"factory_visited_island\"] = true;", LuaTranslatorCode.GeneratedLuaCode749 },
            { "return not Variable[\"factory_visited_island\"]", LuaTranslatorCode.GeneratedLuaCode750 },
            { "Variable[\"factory_govi_active\"] = true;", LuaTranslatorCode.GeneratedLuaCode751 },
            { "return InventoryContains(\"Govi\")", LuaTranslatorCode.GeneratedLuaCode752 },
            { "Variable[\"yacht_hannah_state\"] = \"Distracted\"", LuaTranslatorCode.GeneratedLuaCode753 },
            { "Variable[\"yacht_engine_room_state\"] = \"Jammed\";\nVariable[\"yacht_hannah_state\"] = \"Subdued\";", LuaTranslatorCode.GeneratedLuaCode754 },
            { "return Variable[\"yacht_hannah_state\"] == \"Distracted\"", LuaTranslatorCode.GeneratedLuaCode755 },
            { "return Variable[\"yacht_hannah_state\"] ~= \"Distracted\"", LuaTranslatorCode.GeneratedLuaCode756 },
            { "return not Variable[\"yacht_firebox_open\"]", LuaTranslatorCode.GeneratedLuaCode757 },
            { "return Variable[\"yacht_firebox_open\"]", LuaTranslatorCode.GeneratedLuaCode758 },
            { "Variable[\"yacht_firebox_open\"] = true", LuaTranslatorCode.GeneratedLuaCode759 },
            { "Variable[\"yacht_firebox_open\"] = false;", LuaTranslatorCode.GeneratedLuaCode760 },
            { "Variable[\"yacht_pat_down_complete\"] = true;", LuaTranslatorCode.GeneratedLuaCode761 },
            { "return not (InventoryContains(\"Golden Toilet Handle\") or Variable[\"yacht_swallowed_toilet_handle\"])", LuaTranslatorCode.GeneratedLuaCode762 },
            { "return not Variable[\"yacht_stall_closed\"]", LuaTranslatorCode.GeneratedLuaCode763 },
            { "return Variable[\"yacht_stall_closed\"]", LuaTranslatorCode.GeneratedLuaCode764 },
            { "return InventoryContains(\"Golden Toilet Handle\") or Variable[\"yacht_swallowed_toilet_handle\"]", LuaTranslatorCode.GeneratedLuaCode765 },
            { "return Variable[\"yacht_stall_entered\"]", LuaTranslatorCode.GeneratedLuaCode766 },
            { "x = RandomChoice(\"Yacht Plead with Billy\",3);", LuaTranslatorCode.GeneratedLuaCode767 },
            { "Variable[\"yacht_mary_is_dead\"] = true;", LuaTranslatorCode.GeneratedLuaCode768 },
            { "Variable[\"yacht_ritual_over\"] = true;", LuaTranslatorCode.GeneratedLuaCode769 },
            { "x = RandomChoice(\"Gunshot Whoa\",3);", LuaTranslatorCode.GeneratedLuaCode770 },
            { "Variable[\"global_act_2_quest_stage\"] = \"DrainTheLake\";\nVariable[\"global_vd_outfit\"] = 3;", LuaTranslatorCode.GeneratedLuaCode771 },
            { "Variable[\"global_act_2_quest_stage\"] = \"PowerTheCrane\"", LuaTranslatorCode.GeneratedLuaCode772 },
            { "Variable[\"global_act_2_quest_stage\"] = \"FollowBadGuys\"", LuaTranslatorCode.GeneratedLuaCode773 },
            { "return not (Variable[\"yacht_kenneth_hexed\"] and Variable[\"yacht_barb_hexed\"])", LuaTranslatorCode.GeneratedLuaCode774 },
            { "return Variable[\"yacht_drink_count\"] < 2", LuaTranslatorCode.GeneratedLuaCode775 },
            { "Variable[\"yacht_drink_count\"] = Variable[\"yacht_drink_count\"] - 1;\nUnsetDialogueMemory(270,3);", LuaTranslatorCode.GeneratedLuaCode776 },
            { "return Variable[\"yacht_drink_count\"] >= 2", LuaTranslatorCode.GeneratedLuaCode777 },
            { "Variable[\"yacht_acquired_syrup\"] = true;", LuaTranslatorCode.GeneratedLuaCode778 },
            { "return not Variable[\"yacht_acquired_syrup\"]", LuaTranslatorCode.GeneratedLuaCode779 },
            { "Variable[\"yacht_barb_mentioned_kenneth\"] = true", LuaTranslatorCode.GeneratedLuaCode780 },
            { "return Variable[\"yacht_barb_mentioned_kenneth\"]", LuaTranslatorCode.GeneratedLuaCode781 },
            { "return Variable[\"yacht_kenneth_hexed\"] and Variable[\"yacht_barb_hexed\"]", LuaTranslatorCode.GeneratedLuaCode782 },
            { "should_return_to_barb_convo = true;", LuaTranslatorCode.GeneratedLuaCode783 },
            { "return not Variable[\"yacht_barb_hexed\"] and (InventoryContains(\"Apple of my Eye (Left)\") or InventoryContains(\"Apple of my Eye (Right)\"))", LuaTranslatorCode.GeneratedLuaCode784 },
            { "should_return_to_kenneth_convo = true;", LuaTranslatorCode.GeneratedLuaCode785 },
            { "return InventoryContains(\"Pencil and Paper\");", LuaTranslatorCode.GeneratedLuaCode786 },
            { "return not Variable[\"yacht_kenneth_hexed\"] and (InventoryContains(\"Apple of my Eye (Left)\") or InventoryContains(\"Apple of my Eye (Right)\"))", LuaTranslatorCode.GeneratedLuaCode787 },
            { "should_return_to_barb_convo = false;", LuaTranslatorCode.GeneratedLuaCode788 },
            { "Variable[\"yacht_barb_hexed\"] = true;", LuaTranslatorCode.GeneratedLuaCode789 },
            { "return Variable[\"yacht_kenneth_hexed\"]", LuaTranslatorCode.GeneratedLuaCode790 },
            { "return Variable[\"yacht_barb_hexed\"]", LuaTranslatorCode.GeneratedLuaCode791 },
            { "return not Variable[\"yacht_barb_hexed\"]", LuaTranslatorCode.GeneratedLuaCode792 },
            { "return not Variable[\"yacht_kenneth_hexed\"]", LuaTranslatorCode.GeneratedLuaCode793 },
            { "return should_return_to_barb_convo", LuaTranslatorCode.GeneratedLuaCode794 },
            { "return not should_return_to_barb_convo", LuaTranslatorCode.GeneratedLuaCode795 },
            { "Variable[\"yacht_kenneth_hexed\"] = true;", LuaTranslatorCode.GeneratedLuaCode796 },
            { "should_return_to_kenneth_convo = false;", LuaTranslatorCode.GeneratedLuaCode797 },
            { "return not should_return_to_kenneth_convo", LuaTranslatorCode.GeneratedLuaCode798 },
            { "return should_return_to_kenneth_convo", LuaTranslatorCode.GeneratedLuaCode799 },
            { "x = RandomChoice(\"Examine Party Guests\",2);", LuaTranslatorCode.GeneratedLuaCode800 },
            { "Variable[\"yacht_apple_acquired\"] = true;", LuaTranslatorCode.GeneratedLuaCode801 },
            { "return not Variable[\"yacht_apple_acquired\"]", LuaTranslatorCode.GeneratedLuaCode802 },
            { "return Variable[\"yacht_apple_acquired\"]", LuaTranslatorCode.GeneratedLuaCode803 },
            { "Variable[\"yacht_hannah_state\"] = \"Alert\";\nVariable[\"yacht_firebox_open\"] = false;", LuaTranslatorCode.GeneratedLuaCode804 },
            { "InventoryRemoveItem(\"Golden Toilet Handle\")", LuaTranslatorCode.GeneratedLuaCode805 },
            { "Variable[\"yacht_fusebox_fixed\"] = true;", LuaTranslatorCode.GeneratedLuaCode806 },
            { "Variable[\"yacht_examined_fusebox\"] = true;", LuaTranslatorCode.GeneratedLuaCode807 },
            { "Variable[\"yacht_examined_lifeboat\"] = true;", LuaTranslatorCode.GeneratedLuaCode808 },
            { "return Variable[\"global_vd_outfit\"] == 0", LuaTranslatorCode.GeneratedLuaCode809 },
            { "return Variable[\"global_vd_outfit\"] == 1", LuaTranslatorCode.GeneratedLuaCode810 },
            { "return Variable[\"global_vd_outfit\"] == 2", LuaTranslatorCode.GeneratedLuaCode811 },
            { "return Variable[\"global_vd_outfit\"] == 3", LuaTranslatorCode.GeneratedLuaCode812 },
            { "return Variable[\"global_current_act\"] ~= 2", LuaTranslatorCode.GeneratedLuaCode813 },
            { "return not Variable[\"office_donned_coat\"]", LuaTranslatorCode.GeneratedLuaCode814 },
            { "return Variable[\"global_current_act\"] == 1 and Variable[\"global_act_1_quest_stage\"] == \"BombDeployed\"", LuaTranslatorCode.GeneratedLuaCode815 },
            { "return false", LuaTranslatorCode.GeneratedLuaCode816 },
            { "return Variable[\"global_act_1_quest_stage\"] ~= \"NewGame\"", LuaTranslatorCode.GeneratedLuaCode817 },
            { "return Variable[\"global_current_act\"] - 1", LuaTranslatorCode.GeneratedLuaCode818 },
            { "return Variable[\"global_current_act\"] ~= 1 or Variable[\"global_act_1_quest_stage\"] ~= \"VDWasBombed\"", LuaTranslatorCode.GeneratedLuaCode819 },
            { "return Variable[\"dhb_trance_stage\"] == \"Hurt\" or Variable[\"dhb_trance_stage\"] == \"Slapped\" or Variable[\"dhb_trance_stage\"] == \"Awake\"", LuaTranslatorCode.GeneratedLuaCode820 },
            { "return Variable[\"ll_is_stake_out\"]", LuaTranslatorCode.GeneratedLuaCode821 },
            { "return not Variable[\"ll_is_stake_out\"]", LuaTranslatorCode.GeneratedLuaCode822 },
            { "return Variable[\"ll_cabinet_open\"]", LuaTranslatorCode.GeneratedLuaCode823 },
            { "return not Variable[\"cemetery_govi_complete\"]", LuaTranslatorCode.GeneratedLuaCode824 },
            { "return Variable[\"cemetery_lemoon_unlocked\"]", LuaTranslatorCode.GeneratedLuaCode825 },
            { "return not Variable[\"chic_kiki_left_restaurant\"] and Variable[\"global_current_act\"] == 1", LuaTranslatorCode.GeneratedLuaCode826 },
            { "return not Variable[\"chic_elevator_unlocked\"]", LuaTranslatorCode.GeneratedLuaCode827 },
            { "return Variable[\"global_act_2_quest_stage\"] == \"Slideshow\"", LuaTranslatorCode.GeneratedLuaCode828 },
            { "return not Variable[\"if_acquired_feather\"]", LuaTranslatorCode.GeneratedLuaCode829 },
            { "return not Variable[\"pl_have_visited\"]", LuaTranslatorCode.GeneratedLuaCode830 },
            { "return Variable[\"pl_have_visited\"]", LuaTranslatorCode.GeneratedLuaCode831 },
            { "return Variable[\"factory_used_govi\"]", LuaTranslatorCode.GeneratedLuaCode832 },
        };
    }
}
